-- Repo Company Quidditch: reliable Golden Snitch zero-second handoff
-- Run this entire file once in Supabase -> SQL Editor.
--
-- This migration is safe to re-run. It does not reset accounts, scores, cards,
-- GP, career records or existing Quidditch history.
--
-- It fixes the case where the browser reaches FULL TIME 0:00 but the shared
-- match row did not receive (or finish processing) the original Snitch catch.
-- At zero, every viewer may ask for the handoff; row locks and idempotent keys
-- ensure the next match is created only once.

begin;

create table if not exists public.quidditch_live_clock (
  clock_id smallint primary key default 1 check (clock_id = 1),
  match_id bigint not null,
  phase text not null check (phase in ('lineup','live','post')),
  phase_started_at timestamptz not null,
  phase_ends_at timestamptz not null,
  updated_at timestamptz not null default clock_timestamp()
);

create table if not exists public.quidditch_snitch_match_results (
  match_id bigint primary key,
  winner_side text not null check (winner_side in ('left','right')),
  winner_pet text not null,
  caught_at timestamptz not null default clock_timestamp(),
  post_ends_at timestamptz not null
);

create table if not exists public.quidditch_goals (
  id bigint generated by default as identity primary key,
  match_id bigint not null,
  event_key text not null unique,
  side text not null check (side in ('left','right')),
  pet_name text not null,
  scored_at timestamptz not null default clock_timestamp()
);

create index if not exists quidditch_goals_match_idx
  on public.quidditch_goals(match_id, scored_at, id);

-- Unambiguous bigint version of the Snitch finish RPC. It is idempotent and can
-- repair a catch if the earlier browser request was interrupted.
create or replace function public.finish_live_quidditch_by_snitch_v2(
  p_match_id bigint,
  p_winner_side text,
  p_winner_pet text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_clock public.quidditch_live_clock%rowtype;
  v_result public.quidditch_snitch_match_results%rowtype;
  v_side text := lower(btrim(coalesce(p_winner_side, '')));
  v_pet text := left(coalesce(nullif(btrim(p_winner_pet), ''), 'Pet'), 80);
  v_left integer := 0;
  v_right integer := 0;
  v_needed integer := 0;
  v_i integer;
  v_goal_id bigint;
  v_left_scorers jsonb := '{}'::jsonb;
  v_right_scorers jsonb := '{}'::jsonb;
  v_applied boolean := false;
begin
  if p_match_id is null or p_match_id <= 0 then
    raise exception 'Invalid match id';
  end if;
  if v_side not in ('left', 'right') then
    raise exception 'Invalid Snitch winner';
  end if;

  perform pg_advisory_xact_lock(hashtext('repo-live-quidditch:' || p_match_id::text));

  select q.* into v_clock
  from public.quidditch_live_clock q
  where q.clock_id = 1
  for update;

  if not found then
    raise exception 'Quidditch live clock is not installed';
  end if;

  select r.* into v_result
  from public.quidditch_snitch_match_results r
  where r.match_id = p_match_id;

  if not found then
    if v_clock.match_id <> p_match_id or v_clock.phase not in ('live', 'post') then
      raise exception 'This match can no longer be finished by the Snitch';
    end if;

    select
      count(*) filter (where g.side = 'left')::integer,
      count(*) filter (where g.side = 'right')::integer
    into v_left, v_right
    from public.quidditch_goals g
    where g.match_id = p_match_id;

    v_needed := case
      when v_side = 'left' then greatest(1, v_right - v_left + 1)
      else greatest(1, v_left - v_right + 1)
    end;
    v_needed := least(v_needed, 30);

    for v_i in 1..v_needed loop
      insert into public.quidditch_goals(match_id, event_key, side, pet_name, scored_at)
      values(
        p_match_id,
        'snitch-v2:' || p_match_id::text || ':' || v_side || ':' || v_i::text,
        v_side,
        v_pet,
        v_now
      )
      on conflict(event_key) do nothing;
    end loop;

    insert into public.quidditch_snitch_match_results(
      match_id, winner_side, winner_pet, caught_at, post_ends_at
    )
    values(
      p_match_id, v_side, v_pet, v_now, v_now + interval '30 seconds'
    )
    on conflict(match_id) do update
      set winner_side = excluded.winner_side,
          winner_pet = excluded.winner_pet
    returning * into v_result;

    v_applied := true;
  end if;

  -- Reassert the authoritative POST phase if an older request left the row LIVE.
  if v_clock.match_id = p_match_id and v_clock.phase <> 'lineup' then
    update public.quidditch_live_clock q
       set phase = 'post',
           phase_started_at = v_result.caught_at,
           phase_ends_at = v_result.post_ends_at,
           updated_at = v_now
     where q.clock_id = 1
       and q.match_id = p_match_id;
  end if;

  select
    coalesce(sum(g.goals) filter (where g.side = 'left'), 0)::integer,
    coalesce(sum(g.goals) filter (where g.side = 'right'), 0)::integer,
    coalesce(
      jsonb_object_agg(g.pet_name, g.goals) filter (where g.side = 'left'),
      '{}'::jsonb
    ),
    coalesce(
      jsonb_object_agg(g.pet_name, g.goals) filter (where g.side = 'right'),
      '{}'::jsonb
    )
  into v_left, v_right, v_left_scorers, v_right_scorers
  from (
    select qg.side, qg.pet_name, count(*)::integer as goals
    from public.quidditch_goals qg
    where qg.match_id = p_match_id
    group by qg.side, qg.pet_name
  ) g;

  select g.id into v_goal_id
  from public.quidditch_goals g
  where g.match_id = p_match_id
  order by g.id desc
  limit 1;

  return jsonb_build_object(
    'goal_id', v_goal_id,
    'left_score', coalesce(v_left, 0),
    'right_score', coalesce(v_right, 0),
    'left_scorers', coalesce(v_left_scorers, '{}'::jsonb),
    'right_scorers', coalesce(v_right_scorers, '{}'::jsonb),
    'match_id', p_match_id,
    'phase', 'post',
    'phase_seconds', greatest(
      0,
      ceil(extract(epoch from (v_result.post_ends_at - clock_timestamp())))::integer
    ),
    'ended_by_snitch', true,
    'snitch_winner_side', v_result.winner_side,
    'snitch_winner_pet', v_result.winner_pet,
    'post_ends_at', v_result.post_ends_at,
    'applied', v_applied
  );
end;
$$;

-- Hard handoff used only after the visible Snitch countdown reaches zero.
-- If the original finish call was lost, this reconstructs the result with an
-- already-completed 30-second post phase and immediately opens the next lineup.
create or replace function public.force_advance_quidditch_after_snitch(
  p_match_id bigint,
  p_winner_side text,
  p_winner_pet text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_clock public.quidditch_live_clock%rowtype;
  v_result public.quidditch_snitch_match_results%rowtype;
  v_side text := lower(btrim(coalesce(p_winner_side, '')));
  v_pet text := left(coalesce(nullif(btrim(p_winner_pet), ''), 'Pet'), 80);
  v_left integer := 0;
  v_right integer := 0;
  v_needed integer := 0;
  v_i integer;
  v_advanced boolean := false;
  v_caught_at timestamptz;
  v_fallback_side text;
  v_fallback_pet text;
begin
  if p_match_id is null or p_match_id <= 0 then
    raise exception 'Invalid match id';
  end if;
  if v_side not in ('left', 'right') then
    raise exception 'Invalid Snitch winner';
  end if;

  perform pg_advisory_xact_lock(hashtext('repo-live-quidditch:' || p_match_id::text));

  select q.* into v_clock
  from public.quidditch_live_clock q
  where q.clock_id = 1
  for update;

  if not found then
    raise exception 'Quidditch live clock is not installed';
  end if;

  -- Another viewer may already have completed the transition.
  if v_clock.match_id > p_match_id then
    return jsonb_build_object(
      'advanced', false,
      'already_advanced', true,
      'match_id', v_clock.match_id,
      'phase', v_clock.phase,
      'phase_seconds', greatest(
        0,
        ceil(extract(epoch from (v_clock.phase_ends_at - v_now)))::integer
      )
    );
  end if;

  if v_clock.match_id < p_match_id then
    raise exception 'The requested match has not started';
  end if;

  select r.* into v_result
  from public.quidditch_snitch_match_results r
  where r.match_id = p_match_id;

  -- Recover older fallback goal rows when available.
  if not found then
    select min(g.scored_at), min(g.side), min(g.pet_name)
      into v_caught_at, v_fallback_side, v_fallback_pet
    from public.quidditch_goals g
    where g.match_id = p_match_id
      and (
        g.event_key like ('snitch:' || p_match_id::text || ':%')
        or g.event_key like ('snitch-v2:' || p_match_id::text || ':%')
      );

    if v_caught_at is not null and v_fallback_side in ('left', 'right') then
      insert into public.quidditch_snitch_match_results(
        match_id, winner_side, winner_pet, caught_at, post_ends_at
      )
      values(
        p_match_id,
        v_fallback_side,
        coalesce(nullif(v_fallback_pet, ''), v_pet),
        v_caught_at,
        v_caught_at + interval '30 seconds'
      )
      on conflict(match_id) do nothing;
    else
      -- The browser has already shown the complete 30-second FULL TIME screen.
      -- Reconstruct the winning score and mark that presentation as completed.
      select
        count(*) filter (where g.side = 'left')::integer,
        count(*) filter (where g.side = 'right')::integer
      into v_left, v_right
      from public.quidditch_goals g
      where g.match_id = p_match_id;

      v_needed := case
        when v_side = 'left' then greatest(1, v_right - v_left + 1)
        else greatest(1, v_left - v_right + 1)
      end;
      v_needed := least(v_needed, 30);

      for v_i in 1..v_needed loop
        insert into public.quidditch_goals(match_id, event_key, side, pet_name, scored_at)
        values(
          p_match_id,
          'snitch-force:' || p_match_id::text || ':' || v_side || ':' || v_i::text,
          v_side,
          v_pet,
          v_now
        )
        on conflict(event_key) do nothing;
      end loop;

      insert into public.quidditch_snitch_match_results(
        match_id, winner_side, winner_pet, caught_at, post_ends_at
      )
      values(
        p_match_id,
        v_side,
        v_pet,
        v_now - interval '30 seconds',
        v_now
      )
      on conflict(match_id) do nothing;
    end if;

    select r.* into v_result
    from public.quidditch_snitch_match_results r
    where r.match_id = p_match_id;
  end if;

  if v_result.post_ends_at <= v_now then
    update public.quidditch_live_clock q
       set match_id = p_match_id + 1,
           phase = 'lineup',
           phase_started_at = v_now,
           phase_ends_at = v_now + interval '25 seconds',
           updated_at = v_now
     where q.clock_id = 1
       and q.match_id = p_match_id
    returning q.* into v_clock;

    v_advanced := found;
  else
    -- The catch reached the server slightly later than the animation. Preserve
    -- its exact deadline; clients retry this idempotent function at zero.
    update public.quidditch_live_clock q
       set phase = 'post',
           phase_started_at = v_result.caught_at,
           phase_ends_at = v_result.post_ends_at,
           updated_at = v_now
     where q.clock_id = 1
       and q.match_id = p_match_id
    returning q.* into v_clock;
  end if;

  return jsonb_build_object(
    'advanced', v_advanced,
    'already_advanced', false,
    'match_id', v_clock.match_id,
    'phase', v_clock.phase,
    'phase_seconds', greatest(
      0,
      ceil(extract(epoch from (v_clock.phase_ends_at - clock_timestamp())))::integer
    )
  );
end;
$$;

revoke all on function public.finish_live_quidditch_by_snitch_v2(bigint, text, text)
  from public;
revoke all on function public.force_advance_quidditch_after_snitch(bigint, text, text)
  from public;

grant execute on function public.finish_live_quidditch_by_snitch_v2(bigint, text, text)
  to anon, authenticated;
grant execute on function public.force_advance_quidditch_after_snitch(bigint, text, text)
  to anon, authenticated;

-- Immediately repair the currently displayed match when a retained Snitch result
-- has already passed its 30-second deadline.
do $$
declare
  v_match_id bigint;
  v_side text;
  v_pet text;
begin
  select q.match_id into v_match_id
  from public.quidditch_live_clock q
  where q.clock_id = 1;

  select r.winner_side, r.winner_pet
    into v_side, v_pet
  from public.quidditch_snitch_match_results r
  where r.match_id = v_match_id
    and r.post_ends_at <= clock_timestamp();

  if v_side in ('left', 'right') then
    perform public.force_advance_quidditch_after_snitch(v_match_id, v_side, v_pet);
  end if;
end;
$$;

notify pgrst, 'reload schema';

commit;
