-- REPO COMPANY: MULTIPLAYER HORDE LEADERBOARDS
-- Run once in Supabase -> SQL Editor.

create table if not exists public.multiplayer_horde_scores (
  id bigint generated by default as identity primary key,
  host_user_id uuid not null references auth.users(id) on delete cascade,
  host_name text not null,
  guest_name text not null,
  map_id text not null check (map_id in ('zombie-varrock','zombie-falador','zombie-morytania')),
  best_wave integer not null default 1,
  best_kills integer not null default 0,
  best_seconds integer not null default 0,
  host_weapon text not null,
  guest_weapon text not null,
  host_upgrades jsonb not null default '[]'::jsonb,
  guest_upgrades jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  unique(host_user_id, guest_name, map_id)
);

alter table public.multiplayer_horde_scores enable row level security;

create or replace function public.submit_multiplayer_horde_score(
  p_map_id text,
  p_guest_name text,
  p_wave integer,
  p_kills integer,
  p_seconds integer,
  p_host_weapon text,
  p_guest_weapon text,
  p_host_upgrades jsonb default '[]'::jsonb,
  p_guest_upgrades jsonb default '[]'::jsonb
) returns void
language plpgsql
security definer
set search_path=public,auth
as $$
declare
  v_host_name text;
  v_existing public.multiplayer_horde_scores%rowtype;
  v_better boolean;
begin
  if auth.uid() is null then raise exception 'Sign in required'; end if;
  if p_map_id not in ('zombie-varrock','zombie-falador','zombie-morytania') then raise exception 'Invalid map'; end if;
  if p_host_weapon not in ('greataxe','blowpipe','shadow','dharok') then raise exception 'Invalid host weapon'; end if;
  if p_guest_weapon not in ('greataxe','blowpipe','shadow','dharok') then raise exception 'Invalid guest weapon'; end if;

  select username into v_host_name from public.characters where user_id=auth.uid() limit 1;
  if v_host_name is null then raise exception 'Character not found'; end if;

  select * into v_existing
  from public.multiplayer_horde_scores
  where host_user_id=auth.uid() and lower(guest_name)=lower(btrim(p_guest_name)) and map_id=p_map_id
  for update;

  if not found then
    insert into public.multiplayer_horde_scores(
      host_user_id,host_name,guest_name,map_id,best_wave,best_kills,best_seconds,
      host_weapon,guest_weapon,host_upgrades,guest_upgrades
    ) values (
      auth.uid(),v_host_name,btrim(p_guest_name),p_map_id,greatest(1,p_wave),greatest(0,p_kills),greatest(0,p_seconds),
      p_host_weapon,p_guest_weapon,coalesce(p_host_upgrades,'[]'::jsonb),coalesce(p_guest_upgrades,'[]'::jsonb)
    );
    return;
  end if;

  v_better := p_wave > v_existing.best_wave
    or (p_wave = v_existing.best_wave and p_kills > v_existing.best_kills)
    or (p_wave = v_existing.best_wave and p_kills = v_existing.best_kills and p_seconds > v_existing.best_seconds);

  if v_better then
    update public.multiplayer_horde_scores
       set host_name=v_host_name,
           guest_name=btrim(p_guest_name),
           best_wave=greatest(1,p_wave),
           best_kills=greatest(0,p_kills),
           best_seconds=greatest(0,p_seconds),
           host_weapon=p_host_weapon,
           guest_weapon=p_guest_weapon,
           host_upgrades=coalesce(p_host_upgrades,'[]'::jsonb),
           guest_upgrades=coalesce(p_guest_upgrades,'[]'::jsonb),
           updated_at=now()
     where id=v_existing.id;
  end if;
end;
$$;

create or replace function public.get_multiplayer_horde_leaderboard()
returns table(
  host_name text,
  guest_name text,
  map_id text,
  best_wave integer,
  best_kills integer,
  best_seconds integer,
  host_weapon text,
  guest_weapon text,
  host_upgrades jsonb,
  guest_upgrades jsonb
)
language sql
stable
security definer
set search_path=public
as $$
  select s.host_name,s.guest_name,s.map_id,s.best_wave,s.best_kills,s.best_seconds,
         s.host_weapon,s.guest_weapon,s.host_upgrades,s.guest_upgrades
  from public.multiplayer_horde_scores s
  order by s.map_id,s.best_wave desc,s.best_kills desc,s.best_seconds desc
  limit 75
$$;

grant execute on function public.submit_multiplayer_horde_score(text,text,integer,integer,integer,text,text,jsonb,jsonb) to authenticated;
grant execute on function public.get_multiplayer_horde_leaderboard() to anon,authenticated;

notify pgrst,'reload schema';
