-- REPO COMPANY: SHARED PET-ROOM CHAT
-- Run this file once in Supabase > SQL Editor.
-- It does not reset characters, pets, XP, items, or any existing data.

create table if not exists public.pet_room_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  message text not null check (char_length(message) between 1 and 120),
  created_at timestamptz not null default now()
);

create index if not exists pet_room_messages_created_idx
  on public.pet_room_messages (id desc);

alter table public.pet_room_messages enable row level security;

-- Direct table writes stay blocked. Chat is sent through the validated RPC below.
revoke all on table public.pet_room_messages from anon, authenticated;

drop function if exists public.send_pet_room_message(text);
create function public.send_pet_room_message(p_message text)
returns table(id bigint, username text, message text, created_at timestamptz)
language plpgsql
security definer
set search_path=public
as $$
declare
  uid uuid:=auth.uid();
  clean_message text:=btrim(coalesce(p_message,''));
  player_name text;
  has_pet boolean;
  last_sent timestamptz;
  new_id bigint;
begin
  if uid is null then raise exception 'You must be logged in'; end if;
  if clean_message='' then raise exception 'Type a message first'; end if;
  if char_length(clean_message)>120 then raise exception 'Messages can be at most 120 characters'; end if;

  select c.username, c.active_pet is not null
    into player_name, has_pet
  from public.characters c
  where c.user_id=uid;

  if player_name is null then raise exception 'Create a character first'; end if;
  if not coalesce(has_pet,false) then raise exception 'Choose an active pet before chatting'; end if;

  select m.created_at into last_sent
  from public.pet_room_messages m
  where m.user_id=uid
  order by m.id desc limit 1;

  if last_sent is not null and last_sent > now()-interval '1 second' then
    raise exception 'Your pet needs a moment before speaking again';
  end if;

  insert into public.pet_room_messages(user_id,username,message)
  values(uid,player_name,clean_message)
  returning pet_room_messages.id into new_id;

  -- Keep the table compact. Messages only need to exist briefly for polling clients.
  delete from public.pet_room_messages m where m.created_at < now()-interval '1 day';

  return query
  select m.id,m.username,m.message,m.created_at
  from public.pet_room_messages m where m.id=new_id;
end $$;

grant execute on function public.send_pet_room_message(text) to authenticated;

drop function if exists public.get_pet_room_messages(bigint);
create function public.get_pet_room_messages(p_after_id bigint default 0)
returns table(id bigint, username text, message text, created_at timestamptz)
language sql
security definer
set search_path=public
stable
as $$
  select m.id,m.username,m.message,m.created_at
  from public.pet_room_messages m
  where m.id > greatest(coalesce(p_after_id,0),0)
    and m.created_at > now()-interval '10 minutes'
  order by m.id asc
  limit 50
$$;

grant execute on function public.get_pet_room_messages(bigint) to anon, authenticated;
