-- Tombs of Amascut: reliable two-player room registry.
-- Run once in the Supabase SQL editor before deploying the updated site.

create table if not exists public.toa_rooms (
  id bigint generated by default as identity primary key,
  code text not null unique check (code ~ '^[A-Z2-9]{6}$'),
  host_user_id uuid not null references auth.users(id) on delete cascade,
  host_name text not null,
  guest_user_id uuid references auth.users(id) on delete set null,
  guest_name text,
  status text not null default 'lobby' check (status in ('lobby','playing','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists toa_rooms_code_idx on public.toa_rooms(code);
create index if not exists toa_rooms_updated_idx on public.toa_rooms(updated_at);

alter table public.toa_rooms enable row level security;

drop policy if exists toa_rooms_select on public.toa_rooms;
drop policy if exists toa_rooms_insert on public.toa_rooms;
drop policy if exists toa_rooms_update on public.toa_rooms;
drop policy if exists toa_rooms_delete on public.toa_rooms;

create policy toa_rooms_select on public.toa_rooms
for select to authenticated using (true);

create policy toa_rooms_insert on public.toa_rooms
for insert to authenticated with check (host_user_id = auth.uid());

create policy toa_rooms_update on public.toa_rooms
for update to authenticated
using (host_user_id = auth.uid() or guest_user_id = auth.uid() or guest_user_id is null)
with check (host_user_id = auth.uid() or guest_user_id = auth.uid());

create policy toa_rooms_delete on public.toa_rooms
for delete to authenticated using (host_user_id = auth.uid());

grant select, insert, update, delete on public.toa_rooms to authenticated;
grant usage, select on sequence public.toa_rooms_id_seq to authenticated;

create or replace function public.join_toa_room(p_code text, p_guest_name text)
returns setof public.toa_rooms
language plpgsql
security definer
set search_path = public
as $$
declare
  v_room public.toa_rooms%rowtype;
begin
  select * into v_room
  from public.toa_rooms
  where code = upper(trim(p_code))
    and status <> 'closed'
    and updated_at > now() - interval '6 hours'
  for update;

  if not found then raise exception 'ROOM_NOT_FOUND'; end if;
  if v_room.host_user_id = auth.uid() then return next v_room; return; end if;
  if v_room.guest_user_id is not null and v_room.guest_user_id <> auth.uid() then
    raise exception 'ROOM_FULL';
  end if;

  update public.toa_rooms
  set guest_user_id = auth.uid(), guest_name = left(coalesce(p_guest_name,'Raider'),40), updated_at = now()
  where id = v_room.id
  returning * into v_room;
  return next v_room;
end;
$$;

grant execute on function public.join_toa_room(text,text) to authenticated;
