-- REPO COMPANY — REPO ROOFTOPS
-- Repair/install for the Level Agility Repo Rooftops minigame.
-- Safe to run more than once. Does not replace or rename existing Harmony leaderboard functions.
-- Repo Rooftops GP is rebalanced to 20% of the original values (an 80% reduction).

create extension if not exists pgcrypto;

alter table public.characters add column if not exists gp integer not null default 0;
alter table public.characters add column if not exists agility_xp integer not null default 0;
alter table public.characters add column if not exists bank_items jsonb not null default '{}'::jsonb;

create table if not exists public.repo_rooftops_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  character_config jsonb not null default '{}'::jsonb,
  settings jsonb not null default '{}'::jsonb,
  best_height integer not null default 0 check (best_height >= 0),
  best_level integer not null default 0 check (best_level >= 0),
  mark_balance integer not null default 0 check (mark_balance >= 0),
  total_runs integer not null default 0 check (total_runs >= 0),
  total_gp_earned bigint not null default 0 check (total_gp_earned >= 0),
  total_metres bigint not null default 0 check (total_metres >= 0),
  total_playtime_ms bigint not null default 0 check (total_playtime_ms >= 0),
  stats jsonb not null default '{}'::jsonb,
  achievements jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.repo_rooftops_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  mode text not null check (mode in ('endless','daily','hardcore','timetrial')),
  seed text not null,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  claimed_at timestamptz,
  status text not null default 'active' check (status in ('active','claimed','abandoned','rejected')),
  highest_height integer not null default 0,
  completed_levels integer not null default 0,
  score bigint not null default 0,
  district text not null default 'Old Town Rooftops',
  max_momentum integer not null default 0,
  collectable_gp integer not null default 0,
  risk_gp integer not null default 0,
  marks_collected integer not null default 0,
  duration_ms bigint not null default 0,
  height_gp integer not null default 0,
  level_gp integer not null default 0,
  difficulty_gp integer not null default 0,
  momentum_gp integer not null default 0,
  personal_best_gp integer not null default 0,
  milestone_gp integer not null default 0,
  agility_xp_gained integer not null default 0,
  total_gp integer not null default 0,
  is_personal_best boolean not null default false,
  suspicious_reason text,
  created_at timestamptz not null default now()
);

create index if not exists repo_rooftops_runs_user_started_idx
  on public.repo_rooftops_runs(user_id, started_at desc);
create index if not exists repo_rooftops_runs_leaderboard_idx
  on public.repo_rooftops_runs(mode, status, highest_height desc, score desc);

create table if not exists public.repo_rooftops_levels (
  run_id uuid not null references public.repo_rooftops_runs(id) on delete cascade,
  level_number integer not null check (level_number > 0),
  level_id text not null,
  has_mark boolean not null default false,
  mark_id uuid,
  previewed_at timestamptz not null default now(),
  completed_at timestamptz,
  completed_height integer,
  primary key(run_id, level_number),
  unique(run_id, level_id)
);

create table if not exists public.repo_rooftops_marks (
  mark_id uuid primary key,
  run_id uuid not null references public.repo_rooftops_runs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  level_number integer not null,
  level_id text not null,
  collected_at timestamptz,
  created_at timestamptz not null default now(),
  unique(run_id, level_number),
  unique(run_id, level_id)
);

create index if not exists repo_rooftops_marks_user_idx
  on public.repo_rooftops_marks(user_id, collected_at desc);

create table if not exists public.repo_rooftops_milestones (
  user_id uuid not null references auth.users(id) on delete cascade,
  height integer not null,
  gp_awarded integer not null check (gp_awarded >= 0),
  run_id uuid not null references public.repo_rooftops_runs(id) on delete cascade,
  claimed_at timestamptz not null default now(),
  primary key(user_id, height)
);

create table if not exists public.repo_rooftops_xp_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  run_id uuid not null unique references public.repo_rooftops_runs(id) on delete cascade,
  xp_gained integer not null check (xp_gained > 0),
  created_at timestamptz not null default now()
);

create index if not exists repo_rooftops_xp_ledger_user_created_idx
  on public.repo_rooftops_xp_ledger(user_id, created_at desc);

alter table public.repo_rooftops_profiles enable row level security;
alter table public.repo_rooftops_runs enable row level security;
alter table public.repo_rooftops_levels enable row level security;
alter table public.repo_rooftops_marks enable row level security;
alter table public.repo_rooftops_milestones enable row level security;
alter table public.repo_rooftops_xp_ledger enable row level security;

revoke all on table public.repo_rooftops_profiles from anon, authenticated;
revoke all on table public.repo_rooftops_runs from anon, authenticated;
revoke all on table public.repo_rooftops_levels from anon, authenticated;
revoke all on table public.repo_rooftops_marks from anon, authenticated;
revoke all on table public.repo_rooftops_milestones from anon, authenticated;
revoke all on table public.repo_rooftops_xp_ledger from anon, authenticated;


-- Recreate only Repo Rooftops RPCs so a partial/failed earlier installation is repaired.
drop function if exists public.repo_rooftops_get_profile();
drop function if exists public.repo_rooftops_save_profile(jsonb,jsonb);
drop function if exists public.repo_rooftops_start_run(text,text);
drop function if exists public.repo_rooftops_preview_level(uuid,integer,text);
drop function if exists public.repo_rooftops_complete_level(uuid,integer,text,integer);
drop function if exists public.repo_rooftops_collect_mark(uuid,uuid);
drop function if exists public.repo_rooftops_claim_run(uuid,integer,integer,bigint,bigint,text,integer,integer,integer,integer);
drop function if exists public.repo_rooftops_get_leaderboard(text,text);

create or replace function public.repo_rooftops_get_profile()
returns table(
  best_height integer,
  best_level integer,
  mark_balance integer,
  total_runs integer,
  total_gp_earned bigint,
  total_metres bigint,
  total_playtime_ms bigint,
  stats jsonb,
  achievements jsonb,
  character_config jsonb,
  settings jsonb
)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_uid uuid := auth.uid();
  v_marks integer := 0;
begin
  if v_uid is null then raise exception 'You must be logged in'; end if;

  select greatest(
    coalesce((coalesce(c.bank_items,'{}'::jsonb)->>'marks_of_grace')::integer,0),
    coalesce((select count(*) from public.repo_rooftops_marks m where m.user_id=v_uid and m.collected_at is not null),0)
  ) into v_marks
  from public.characters c where c.user_id=v_uid;

  insert into public.repo_rooftops_profiles(user_id, mark_balance, stats, achievements)
  values(v_uid, coalesce(v_marks,0),
    jsonb_build_object('districts','[]'::jsonb,'deaths',0,'best_momentum',0,'marks_collected',coalesce(v_marks,0),'daily_completed',0),
    '{}'::jsonb)
  on conflict(user_id) do update set
    mark_balance=greatest(public.repo_rooftops_profiles.mark_balance,excluded.mark_balance),
    updated_at=now();

  return query
  select p.best_height,p.best_level,p.mark_balance,p.total_runs,p.total_gp_earned,
         p.total_metres,p.total_playtime_ms,p.stats,p.achievements,p.character_config,p.settings
  from public.repo_rooftops_profiles p where p.user_id=v_uid;
end;
$$;

create or replace function public.repo_rooftops_save_profile(p_character jsonb, p_settings jsonb)
returns table(saved boolean)
language plpgsql
security definer
set search_path = public, auth
as $$
declare v_uid uuid := auth.uid();
begin
  if v_uid is null then raise exception 'You must be logged in'; end if;
  if p_character is null or jsonb_typeof(p_character) <> 'object' then raise exception 'Invalid character configuration'; end if;
  if p_settings is null or jsonb_typeof(p_settings) <> 'object' then raise exception 'Invalid settings'; end if;
  if length(p_character::text) > 12000 or length(p_settings::text) > 16000 then raise exception 'Configuration is too large'; end if;

  insert into public.repo_rooftops_profiles(user_id,character_config,settings)
  values(v_uid,p_character,p_settings)
  on conflict(user_id) do update set character_config=excluded.character_config,settings=excluded.settings,updated_at=now();
  return query select true;
end;
$$;

create or replace function public.repo_rooftops_start_run(p_mode text, p_seed text default null)
returns table(run_id uuid, seed text, server_started_at timestamptz)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_uid uuid := auth.uid();
  v_mode text := lower(trim(coalesce(p_mode,'')));
  v_seed text;
  v_id uuid;
  v_started timestamptz := clock_timestamp();
begin
  if v_uid is null then raise exception 'You must be logged in'; end if;
  if v_mode not in ('endless','daily','hardcore','timetrial') then raise exception 'Invalid Repo Rooftops mode'; end if;

  update public.repo_rooftops_runs r set status='abandoned',ended_at=coalesce(ended_at,now())
   where r.user_id=v_uid and r.status='active' and r.started_at < now()-interval '8 hours';

  if v_mode='daily' then
    v_seed := 'daily-'||to_char(now() at time zone 'Europe/London','YYYY-MM-DD');
  else
    v_seed := left(coalesce(nullif(trim(p_seed),''),v_mode||'-'||encode(gen_random_bytes(16),'hex')),120);
  end if;

  insert into public.repo_rooftops_runs(user_id,mode,seed,started_at)
  values(v_uid,v_mode,v_seed,v_started)
  returning id into v_id;

  insert into public.repo_rooftops_profiles(user_id) values(v_uid) on conflict(user_id) do nothing;
  return query select v_id,v_seed,v_started;
end;
$$;

create or replace function public.repo_rooftops_preview_level(
  p_run_id uuid,
  p_level_number integer,
  p_level_id text
)
returns table(has_mark boolean, mark_id uuid)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_uid uuid := auth.uid();
  v_run public.repo_rooftops_runs%rowtype;
  v_has boolean;
  v_mark uuid;
  v_existing public.repo_rooftops_levels%rowtype;
  v_level_id text := left(trim(coalesce(p_level_id,'')),160);
  v_roll bigint;
begin
  if v_uid is null then raise exception 'You must be logged in'; end if;
  if p_level_number is null or p_level_number < 1 or p_level_number > 100000 then raise exception 'Invalid rooftop level'; end if;
  if v_level_id='' then raise exception 'Missing rooftop level identifier'; end if;

  select * into v_run from public.repo_rooftops_runs r
   where r.id=p_run_id and r.user_id=v_uid and r.status='active';
  if not found then raise exception 'This Repo Rooftops run is not active'; end if;

  select * into v_existing from public.repo_rooftops_levels l
   where l.run_id=p_run_id and l.level_number=p_level_number;
  if found then
    return query select v_existing.has_mark,v_existing.mark_id;
    return;
  end if;

  v_roll := (('x'||substr(md5(v_run.id::text||':'||v_run.seed||':'||p_level_number::text||':repo-grace'),1,8))::bit(32)::bigint);
  v_has := p_level_number > 3 and mod(v_roll,50)=0;
  v_mark := case when v_has then gen_random_uuid() else null end;

  insert into public.repo_rooftops_levels(run_id,level_number,level_id,has_mark,mark_id)
  values(p_run_id,p_level_number,v_level_id,v_has,v_mark)
  on conflict(run_id,level_number) do nothing;

  if v_has then
    insert into public.repo_rooftops_marks(mark_id,run_id,user_id,level_number,level_id)
    values(v_mark,p_run_id,v_uid,p_level_number,v_level_id)
    on conflict do nothing;
  end if;

  select l.has_mark,l.mark_id into v_has,v_mark from public.repo_rooftops_levels l
   where l.run_id=p_run_id and l.level_number=p_level_number;
  return query select v_has,v_mark;
end;
$$;

create or replace function public.repo_rooftops_complete_level(
  p_run_id uuid,
  p_level_number integer,
  p_level_id text,
  p_height integer
)
returns table(accepted boolean, completed_levels integer)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_uid uuid := auth.uid();
  v_run public.repo_rooftops_runs%rowtype;
  v_current integer;
  v_elapsed numeric;
  v_level_id text := left(trim(coalesce(p_level_id,'')),160);
  v_dummy boolean;
  v_dummy_mark uuid;
begin
  if v_uid is null then raise exception 'You must be logged in'; end if;
  if p_level_number is null or p_level_number < 1 or p_level_number > 100000 then raise exception 'Invalid rooftop level'; end if;
  if p_height is null or p_height < 0 then raise exception 'Invalid height'; end if;

  select * into v_run from public.repo_rooftops_runs r
   where r.id=p_run_id and r.user_id=v_uid for update;
  if not found or v_run.status<>'active' then raise exception 'This Repo Rooftops run is not active'; end if;

  v_elapsed := greatest(1,extract(epoch from(clock_timestamp()-v_run.started_at)));
  if p_height > 250 + floor(v_elapsed*130)::integer then raise exception 'Height progression failed validation'; end if;

  select coalesce(max(l.level_number),0) into v_current
  from public.repo_rooftops_levels l where l.run_id=p_run_id and l.completed_at is not null;

  if p_level_number <= v_current then
    return query select true,v_current;
    return;
  end if;
  if p_level_number <> v_current+1 then raise exception 'Rooftop levels must be completed in sequence'; end if;

  if not exists(select 1 from public.repo_rooftops_levels l where l.run_id=p_run_id and l.level_number=p_level_number) then
    select x.has_mark,x.mark_id into v_dummy,v_dummy_mark
    from public.repo_rooftops_preview_level(p_run_id,p_level_number,v_level_id) x;
  end if;

  update public.repo_rooftops_levels l set completed_at=coalesce(l.completed_at,clock_timestamp()),
      completed_height=greatest(coalesce(l.completed_height,0),p_height)
   where l.run_id=p_run_id and l.level_number=p_level_number and l.level_id=v_level_id;
  if not found then raise exception 'Rooftop level identifier does not match the generated level'; end if;

  update public.repo_rooftops_runs r set completed_levels=p_level_number,
      highest_height=greatest(r.highest_height,p_height)
   where r.id=p_run_id;

  return query select true,p_level_number;
end;
$$;

create or replace function public.repo_rooftops_collect_mark(p_run_id uuid,p_mark_id uuid)
returns table(mark_balance integer, bank_items jsonb, already_collected boolean)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_uid uuid := auth.uid();
  v_mark public.repo_rooftops_marks%rowtype;
  v_items jsonb;
  v_balance integer;
  v_existing boolean;
begin
  if v_uid is null then raise exception 'You must be logged in'; end if;

  select * into v_mark from public.repo_rooftops_marks m
   where m.mark_id=p_mark_id and m.run_id=p_run_id and m.user_id=v_uid for update;
  if not found then raise exception 'This Mark of Grace does not belong to the current run'; end if;
  v_existing := v_mark.collected_at is not null;

  if not v_existing then
    if not exists(
      select 1 from public.repo_rooftops_runs r
       where r.id=p_run_id and r.user_id=v_uid and r.status in ('active','claimed')
         and v_mark.level_number <= r.completed_levels+1
    ) then raise exception 'The Mark of Grace has not been reached yet'; end if;

    update public.repo_rooftops_marks m set collected_at=clock_timestamp()
     where m.mark_id=p_mark_id and m.collected_at is null;
  end if;

  insert into public.repo_rooftops_profiles(user_id) values(v_uid) on conflict(user_id) do nothing;
  select count(*)::integer into v_balance from public.repo_rooftops_marks m
   where m.user_id=v_uid and m.collected_at is not null;
  update public.repo_rooftops_profiles p set mark_balance=v_balance,
      stats=coalesce(p.stats,'{}'::jsonb)||jsonb_build_object('marks_collected',v_balance),updated_at=now()
   where p.user_id=v_uid;

  select coalesce(c.bank_items,'{}'::jsonb) into v_items from public.characters c where c.user_id=v_uid for update;
  if v_items is null then raise exception 'Character not found'; end if;
  v_items := jsonb_set(v_items,'{marks_of_grace}',to_jsonb(v_balance),true);
  update public.characters c set bank_items=v_items where c.user_id=v_uid;

  return query select v_balance,v_items,v_existing;
end;
$$;

create or replace function public.repo_rooftops_claim_run(
  p_run_id uuid,
  p_height integer,
  p_rooftop_level integer,
  p_score bigint,
  p_client_duration_ms bigint,
  p_district text,
  p_momentum integer,
  p_collectable_gp integer,
  p_risk_gp integer,
  p_marks_collected integer default 0
)
returns table(
  height_gp integer,
  level_gp integer,
  difficulty_gp integer,
  collectable_gp integer,
  risk_gp integer,
  momentum_gp integer,
  personal_best_gp integer,
  milestone_gp integer,
  agility_xp_gained integer,
  total_gp integer,
  new_gp integer,
  new_agility_xp integer,
  is_personal_best boolean,
  already_claimed boolean,
  mark_balance integer
)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_uid uuid := auth.uid();
  v_run public.repo_rooftops_runs%rowtype;
  v_profile public.repo_rooftops_profiles%rowtype;
  v_character public.characters%rowtype;
  v_server_ms bigint;
  v_recorded_levels integer;
  v_recorded_height integer;
  v_height integer;
  v_levels integer;
  v_score bigint;
  v_collect integer;
  v_risk integer;
  v_momentum integer;
  v_marks integer;
  v_height_gp integer := 0;
  v_level_gp integer := 0;
  v_difficulty_gp integer := 0;
  v_momentum_gp integer := 0;
  v_pb_gp integer := 0;
  v_milestone_gp integer := 0;
  v_agility integer := 0;
  v_repeatable integer := 0;
  v_total integer := 0;
  v_pb boolean := false;
  v_pct numeric := 0;
  v_remaining integer;
  v_band integer;
  v_m integer;
  v_bonus integer;
  v_new_gp integer;
  v_new_xp integer;
  v_stats jsonb;
  v_ach jsonb;
  v_districts jsonb;
  v_items jsonb;
begin
  if v_uid is null then raise exception 'You must be logged in'; end if;

  select * into v_run from public.repo_rooftops_runs r
   where r.id=p_run_id and r.user_id=v_uid for update;
  if not found then raise exception 'Repo Rooftops run not found'; end if;

  select * into v_character from public.characters c where c.user_id=v_uid for update;
  if not found then raise exception 'Character not found'; end if;
  insert into public.repo_rooftops_profiles(user_id) values(v_uid) on conflict(user_id) do nothing;
  select * into v_profile from public.repo_rooftops_profiles p where p.user_id=v_uid for update;

  if v_run.status='claimed' then
    return query select v_run.height_gp,v_run.level_gp,v_run.difficulty_gp,v_run.collectable_gp,
      v_run.risk_gp,v_run.momentum_gp,v_run.personal_best_gp,v_run.milestone_gp,
      v_run.agility_xp_gained,v_run.total_gp,v_character.gp,v_character.agility_xp,
      v_run.is_personal_best,true,v_profile.mark_balance;
    return;
  end if;
  if v_run.status<>'active' then raise exception 'This run can no longer be rewarded'; end if;

  v_server_ms := greatest(1000,(extract(epoch from(clock_timestamp()-v_run.started_at))*1000)::bigint);
  if p_client_duration_ms is null or p_client_duration_ms < 500 then raise exception 'Invalid run duration'; end if;
  if p_client_duration_ms > v_server_ms+120000 then raise exception 'Run duration failed validation'; end if;

  select coalesce(max(l.level_number),0),coalesce(max(l.completed_height),0)
    into v_recorded_levels,v_recorded_height
  from public.repo_rooftops_levels l where l.run_id=p_run_id and l.completed_at is not null;

  v_height := greatest(0,coalesce(p_height,0));
  v_levels := greatest(0,least(coalesce(p_rooftop_level,0),v_recorded_levels));

  -- New clients synchronise every completed rooftop before claiming. This guarded
  -- fallback recovers older pending runs where completion RPCs were lost, while
  -- still enforcing believable server time, height and rooftop counts.
  if coalesce(p_rooftop_level,0)>v_recorded_levels then
    if coalesce(p_rooftop_level,0) <= greatest(0,floor(v_server_ms/2500.0)::integer)
       and coalesce(p_rooftop_level,0) <= greatest(0,floor((v_height+180)/40.0)::integer)
       and v_height <= 250+floor((v_server_ms/1000.0)*130)::integer then
      v_levels := greatest(0,coalesce(p_rooftop_level,0));
      v_recorded_height := greatest(v_recorded_height,v_height);
      update public.repo_rooftops_runs r
         set completed_levels=greatest(r.completed_levels,v_levels),
             highest_height=greatest(r.highest_height,v_height)
       where r.id=p_run_id;
    else
      raise exception 'One or more rooftop levels were not validated';
    end if;
  end if;

  if v_height > greatest(120,v_recorded_height+120) then raise exception 'Final height exceeds the validated route'; end if;
  if v_height > 250+floor((v_server_ms/1000.0)*130)::integer then raise exception 'Run speed failed validation'; end if;

  v_score := greatest(0,least(coalesce(p_score,0),greatest(10000::bigint,v_height::bigint*2500+v_levels::bigint*25000)));
  v_momentum := greatest(0,least(coalesce(p_momentum,0),100));
  v_collect := greatest(0,least(coalesce(p_collectable_gp,0),floor((v_levels*1200+5000)*0.2)::integer));
  v_risk := greatest(0,least(coalesce(p_risk_gp,0),floor((v_levels*2500+6000)*0.2)::integer));
  select count(*)::integer into v_marks from public.repo_rooftops_marks m
   where m.run_id=p_run_id and m.user_id=v_uid and m.collected_at is not null;

  if v_height>=50 or v_levels>=5 then
    v_remaining:=v_height;
    v_band:=least(v_remaining,500);v_height_gp:=v_height_gp+v_band*2;v_remaining:=v_remaining-v_band;
    if v_remaining>0 then v_band:=least(v_remaining,500);v_height_gp:=v_height_gp+floor(v_band*1.5)::integer;v_remaining:=v_remaining-v_band;end if;
    if v_remaining>0 then v_band:=least(v_remaining,1000);v_height_gp:=v_height_gp+v_band;v_remaining:=v_remaining-v_band;end if;
    if v_remaining>0 then v_height_gp:=v_height_gp+floor(v_remaining*0.6)::integer;end if;

    v_level_gp:=v_levels*15;
    if v_height>=1500 then v_difficulty_gp:=1500+floor((v_height-1500)/700.0)::integer*400;
    elsif v_height>=1000 then v_difficulty_gp:=900;
    elsif v_height>=600 then v_difficulty_gp:=500;
    elsif v_height>=300 then v_difficulty_gp:=250;
    elsif v_height>=100 then v_difficulty_gp:=100;
    end if;

    v_pct:=case when v_momentum>=85 then .12 when v_momentum>=65 then .09 when v_momentum>=45 then .06 when v_momentum>=25 then .03 else 0 end;
    v_momentum_gp:=least(5000,floor((v_height_gp+v_level_gp+v_difficulty_gp+v_collect+v_risk)*v_pct)::integer);
    v_repeatable:=least(25000,v_height_gp+v_level_gp+v_difficulty_gp+v_collect+v_risk+v_momentum_gp);

    v_pb:=v_height>v_profile.best_height;
    if v_pb then v_pb_gp:=least(10000,500+greatest(0,v_height-v_profile.best_height)*5);end if;

    for v_m,v_bonus in select * from (values
      (100,1000),(250,2500),(500,5000),(750,7500),(1000,10000),
      (1500,15000),(2000,20000),(3000,30000),(5000,50000)
    ) as milestones(height,gp)
    loop
      if v_height>=v_m then
        insert into public.repo_rooftops_milestones(user_id,height,gp_awarded,run_id)
        values(v_uid,v_m,v_bonus,p_run_id) on conflict(user_id,height) do nothing;
        if found then v_milestone_gp:=v_milestone_gp+v_bonus;end if;
      end if;
    end loop;

    v_agility:=least(25000,greatest(1,floor(v_height*2.5)::integer+v_levels*35+v_momentum*5));
  else
    v_collect:=0;v_risk:=0;
  end if;

  v_total:=v_repeatable+v_pb_gp+v_milestone_gp;
  v_new_gp:=coalesce(v_character.gp,0)+v_total;
  v_new_xp:=coalesce(v_character.agility_xp,0)+v_agility;
  v_items:=coalesce(v_character.bank_items,'{}'::jsonb);
  v_items:=jsonb_set(v_items,'{marks_of_grace}',to_jsonb(v_profile.mark_balance),true);

  update public.characters c set gp=v_new_gp,agility_xp=v_new_xp,bank_items=v_items where c.user_id=v_uid;
  if v_agility>0 then
    insert into public.repo_rooftops_xp_ledger(user_id,run_id,xp_gained)
    values(v_uid,p_run_id,v_agility) on conflict(run_id) do nothing;
  end if;

  v_stats:=coalesce(v_profile.stats,'{}'::jsonb);
  v_districts:=case when jsonb_typeof(v_stats->'districts')='array' then v_stats->'districts' else '[]'::jsonb end;
  if not v_districts ? left(coalesce(p_district,'Old Town Rooftops'),80) then
    v_districts:=v_districts||to_jsonb(left(coalesce(p_district,'Old Town Rooftops'),80));
  end if;
  v_stats:=v_stats||jsonb_build_object(
    'districts',v_districts,
    'deaths',coalesce((v_stats->>'deaths')::integer,0)+1,
    'best_momentum',greatest(coalesce((v_stats->>'best_momentum')::integer,0),v_momentum),
    'marks_collected',v_profile.mark_balance,
    'daily_completed',coalesce((v_stats->>'daily_completed')::integer,0)+case when v_run.mode='daily' then 1 else 0 end
  );

  v_ach:=coalesce(v_profile.achievements,'{}'::jsonb);
  if v_height>=100 then v_ach:=jsonb_set(v_ach,'{height_100}','true'::jsonb,true);end if;
  if v_height>=500 then v_ach:=jsonb_set(v_ach,'{height_500}','true'::jsonb,true);end if;
  if v_height>=1000 then v_ach:=jsonb_set(v_ach,'{height_1000}','true'::jsonb,true);end if;
  if v_height>=2000 then v_ach:=jsonb_set(v_ach,'{height_2000}','true'::jsonb,true);end if;
  if v_levels>=100 then v_ach:=jsonb_set(v_ach,'{levels_100}','true'::jsonb,true);end if;
  if v_profile.mark_balance>=1 then v_ach:=jsonb_set(v_ach,'{first_mark}','true'::jsonb,true);end if;
  if v_marks>=2 then v_ach:=jsonb_set(v_ach,'{multi_mark}','true'::jsonb,true);end if;
  if v_height>=1500 then v_ach:=jsonb_set(v_ach,'{nightmare}','true'::jsonb,true);end if;
  if v_run.mode='daily' then v_ach:=jsonb_set(v_ach,'{daily}','true'::jsonb,true);end if;
  if jsonb_array_length(v_districts)>=7 then v_ach:=jsonb_set(v_ach,'{districts}','true'::jsonb,true);end if;

  update public.repo_rooftops_profiles p set
    best_height=greatest(p.best_height,v_height),best_level=greatest(p.best_level,v_levels),
    total_runs=p.total_runs+1,total_gp_earned=p.total_gp_earned+v_total,total_metres=p.total_metres+v_height,
    total_playtime_ms=p.total_playtime_ms+v_server_ms,stats=v_stats,achievements=v_ach,updated_at=now()
   where p.user_id=v_uid;

  update public.repo_rooftops_runs r set status='claimed',ended_at=clock_timestamp(),claimed_at=clock_timestamp(),
    highest_height=v_height,completed_levels=v_levels,score=v_score,district=left(coalesce(p_district,'Old Town Rooftops'),80),
    max_momentum=v_momentum,collectable_gp=v_collect,risk_gp=v_risk,marks_collected=v_marks,duration_ms=v_server_ms,
    height_gp=v_height_gp,level_gp=v_level_gp,difficulty_gp=v_difficulty_gp,momentum_gp=v_momentum_gp,
    personal_best_gp=v_pb_gp,milestone_gp=v_milestone_gp,agility_xp_gained=v_agility,total_gp=v_total,is_personal_best=v_pb
   where r.id=p_run_id;

  return query select v_height_gp,v_level_gp,v_difficulty_gp,v_collect,v_risk,v_momentum_gp,
    v_pb_gp,v_milestone_gp,v_agility,v_total,v_new_gp,v_new_xp,v_pb,false,v_profile.mark_balance;
end;
$$;

create or replace function public.repo_rooftops_get_leaderboard(p_mode text default 'endless',p_period text default 'all')
returns table(username text,height integer,rooftop_level integer,score bigint,district text,duration_ms bigint,marks_collected integer)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_mode text:=lower(trim(coalesce(p_mode,'endless')));
  v_period text:=lower(trim(coalesce(p_period,'all')));
  v_from timestamptz;
begin
  if v_mode not in ('endless','daily','hardcore','timetrial') then v_mode:='endless';end if;
  if v_period='day' then v_from:=date_trunc('day',now() at time zone 'Europe/London') at time zone 'Europe/London';
  elsif v_period='week' then v_from:=date_trunc('week',now() at time zone 'Europe/London') at time zone 'Europe/London';
  else v_from:='1970-01-01'::timestamptz;end if;

  return query
  with ranked as (
    select coalesce(nullif(trim(c.username),''),'Adventurer')::text as username,
      r.highest_height as height,r.completed_levels as rooftop_level,r.score,r.district,r.duration_ms,r.marks_collected,
      row_number() over(partition by r.user_id order by r.highest_height desc,r.score desc,r.duration_ms asc) as personal_rank
    from public.repo_rooftops_runs r join public.characters c on c.user_id=r.user_id
    where r.status='claimed' and r.mode=v_mode and r.claimed_at>=v_from
  )
  select q.username,q.height,q.rooftop_level,q.score,q.district,q.duration_ms,q.marks_collected
  from ranked q where q.personal_rank=1
  order by q.height desc,q.score desc,q.duration_ms asc,q.username asc limit 100;
end;
$$;

-- Repo Rooftops XP is recorded in repo_rooftops_xp_ledger.
-- Existing daily/global leaderboard functions are deliberately left untouched.

revoke all on function public.repo_rooftops_get_profile() from public;
revoke all on function public.repo_rooftops_save_profile(jsonb,jsonb) from public;
revoke all on function public.repo_rooftops_start_run(text,text) from public;
revoke all on function public.repo_rooftops_preview_level(uuid,integer,text) from public;
revoke all on function public.repo_rooftops_complete_level(uuid,integer,text,integer) from public;
revoke all on function public.repo_rooftops_collect_mark(uuid,uuid) from public;
revoke all on function public.repo_rooftops_claim_run(uuid,integer,integer,bigint,bigint,text,integer,integer,integer,integer) from public;
revoke all on function public.repo_rooftops_get_leaderboard(text,text) from public;

grant execute on function public.repo_rooftops_get_profile() to authenticated;
grant execute on function public.repo_rooftops_save_profile(jsonb,jsonb) to authenticated;
grant execute on function public.repo_rooftops_start_run(text,text) to authenticated;
grant execute on function public.repo_rooftops_preview_level(uuid,integer,text) to authenticated;
grant execute on function public.repo_rooftops_complete_level(uuid,integer,text,integer) to authenticated;
grant execute on function public.repo_rooftops_collect_mark(uuid,uuid) to authenticated;
grant execute on function public.repo_rooftops_claim_run(uuid,integer,integer,bigint,bigint,text,integer,integer,integer,integer) to authenticated;
grant execute on function public.repo_rooftops_get_leaderboard(text,text) to anon,authenticated;

notify pgrst,'reload schema';
