-- REPO COMPANY — PERMANENT HARMONIZE DAILY/GLOBAL LEADERBOARD FIX
-- Run this entire file once in Supabase SQL Editor.
--
-- Why this is needed:
-- The shared Harmony counter was increasing, but harmonize_once_v2() was not
-- recording which signed-in account earned each +3 XP click. The existing
-- daily/global leaderboard functions therefore had nothing personal to count.
--
-- This patch preserves the existing leaderboard functions by renaming them to
-- *_base once, records personal Harmony XP server-side, and then layers that XP
-- into both boards. It is safe to run again.

create table if not exists public.harmony_xp_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  xp_gained integer not null check (xp_gained > 0),
  created_at timestamptz not null default now()
);

create index if not exists harmony_xp_ledger_user_created_idx
  on public.harmony_xp_ledger (user_id, created_at desc);

alter table public.harmony_xp_ledger enable row level security;
revoke all on table public.harmony_xp_ledger from anon, authenticated;

create table if not exists public.counter (
  id integer primary key,
  count integer not null default 0 check (count >= 0)
);

insert into public.counter (id, count)
values (1, 0)
on conflict (id) do nothing;

-- Preserve the current working leaderboard implementations exactly once.
do $$
begin
  if to_regprocedure('public.get_daily_xp_leaderboard_base()') is null
     and to_regprocedure('public.get_daily_xp_leaderboard()') is not null then
    execute 'alter function public.get_daily_xp_leaderboard() rename to get_daily_xp_leaderboard_base';
  end if;

  if to_regprocedure('public.get_global_xp_leaderboard_base()') is null
     and to_regprocedure('public.get_global_xp_leaderboard()') is not null then
    execute 'alter function public.get_global_xp_leaderboard() rename to get_global_xp_leaderboard_base';
  end if;
end
$$;

create or replace function public.harmonize_once_v2()
returns table(
  previous_xp integer,
  xp_gained integer,
  new_xp integer
)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_previous integer;
  v_new integer;
begin
  select c.count
    into v_previous
    from public.counter c
   where c.id = 1
   for update;

  if v_previous is null then
    insert into public.counter (id, count)
    values (1, 3)
    on conflict (id) do update
      set count = public.counter.count + 3
    returning public.counter.count - 3, public.counter.count
      into v_previous, v_new;
  else
    update public.counter c
       set count = v_previous + 3
     where c.id = 1
     returning c.count into v_new;
  end if;

  -- Anonymous visitors may still help the shared skill, but only authenticated
  -- accounts can receive personal daily/global leaderboard credit.
  if auth.uid() is not null then
    insert into public.harmony_xp_ledger(user_id, xp_gained)
    values (auth.uid(), 3);
  end if;

  return query select v_previous, 3, v_new;
end;
$$;

revoke all on function public.harmonize_once_v2() from public;
grant execute on function public.harmonize_once_v2() to anon, authenticated;

-- Daily board: retain all existing XP, then add today's personal Harmony XP.
create or replace function public.get_daily_xp_leaderboard()
returns table(username text, xp_earned bigint)
language sql
security definer
set search_path = public, auth
as $$
  with base as (
    select b.username::text, b.xp_earned::bigint
      from public.get_daily_xp_leaderboard_base() b
  ),
  harmony as (
    select coalesce(nullif(trim(c.username), ''), 'Adventurer')::text as username,
           sum(h.xp_gained)::bigint as xp_earned
      from public.harmony_xp_ledger h
      join public.characters c on c.user_id = h.user_id
     where h.created_at >= date_trunc('day', now() at time zone 'Europe/London') at time zone 'Europe/London'
       and h.created_at <  (date_trunc('day', now() at time zone 'Europe/London') + interval '1 day') at time zone 'Europe/London'
     group by c.user_id, c.username
  ),
  combined as (
    select * from base
    union all
    select * from harmony
  )
  select combined.username, sum(combined.xp_earned)::bigint as xp_earned
    from combined
   group by combined.username
   order by xp_earned desc, combined.username asc
   limit 100;
$$;

-- Global board: retain all existing total XP, then add lifetime personal Harmony XP.
create or replace function public.get_global_xp_leaderboard()
returns table(username text, total_xp bigint)
language sql
security definer
set search_path = public, auth
as $$
  with base as (
    select b.username::text, b.total_xp::bigint
      from public.get_global_xp_leaderboard_base() b
  ),
  harmony as (
    select coalesce(nullif(trim(c.username), ''), 'Adventurer')::text as username,
           sum(h.xp_gained)::bigint as total_xp
      from public.harmony_xp_ledger h
      join public.characters c on c.user_id = h.user_id
     group by c.user_id, c.username
  ),
  combined as (
    select * from base
    union all
    select * from harmony
  )
  select combined.username, sum(combined.total_xp)::bigint as total_xp
    from combined
   group by combined.username
   order by total_xp desc, combined.username asc
   limit 100;
$$;

revoke all on function public.get_daily_xp_leaderboard() from public;
revoke all on function public.get_global_xp_leaderboard() from public;
grant execute on function public.get_daily_xp_leaderboard() to anon, authenticated;
grant execute on function public.get_global_xp_leaderboard() to anon, authenticated;

notify pgrst, 'reload schema';
