-- REPO DIVER — additive secure progression/reward migration
alter table public.characters add column if not exists fishing_xp integer not null default 0;
alter table public.characters add column if not exists cooking_xp integer not null default 0;
alter table public.characters add column if not exists gp bigint not null default 0;
create table if not exists public.repo_diver_profiles(
 user_id uuid primary key references auth.users(id) on delete cascade,
 day_number integer not null default 1,
 unlocked_biomes jsonb not null default '["karamja"]'::jsonb,
 equipment jsonb not null default '{"tank":1,"cargo":1,"harpoon":1,"suit":1,"boost":1}'::jsonb,
 restaurant jsonb not null default '{"rank":1,"tables":3,"kitchen":1}'::jsonb,
 fish_journal jsonb not null default '{}'::jsonb,
 recipes jsonb not null default '["shrimp_skewer","grilled_trout"]'::jsonb,
 stats jsonb not null default '{"deepest":0,"total_fish":0,"total_revenue":0,"perfect_dishes":0}'::jsonb,
 achievements jsonb not null default '{}'::jsonb,
 updated_at timestamptz not null default now()
);
create table if not exists public.repo_diver_runs(
 id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,
 biome text not null,started_at timestamptz not null default now(),completed_at timestamptz,status text not null default 'active',
 fishing_xp integer not null default 0,cooking_xp integer not null default 0,gp integer not null default 0,
 summary jsonb not null default '{}'::jsonb
);
create index if not exists repo_diver_runs_user_idx on public.repo_diver_runs(user_id,started_at desc);
alter table public.repo_diver_profiles enable row level security;alter table public.repo_diver_runs enable row level security;
revoke all on public.repo_diver_profiles from anon,authenticated;revoke all on public.repo_diver_runs from anon,authenticated;
create or replace function public.repo_diver_get_profile() returns jsonb language plpgsql security definer set search_path=public as $$
declare u uuid:=auth.uid();p public.repo_diver_profiles%rowtype;begin if u is null then raise exception 'You must be logged in';end if;insert into public.repo_diver_profiles(user_id) values(u) on conflict(user_id) do nothing;select * into p from public.repo_diver_profiles where user_id=u;return jsonb_build_object('day_number',p.day_number,'unlocked_biomes',p.unlocked_biomes,'equipment',p.equipment,'restaurant',p.restaurant,'fish_journal',p.fish_journal,'recipes',p.recipes,'stats',p.stats,'achievements',p.achievements);end$$;
create or replace function public.repo_diver_start_day(p_biome text) returns table(run_id uuid,server_started_at timestamptz) language plpgsql security definer set search_path=public as $$
declare u uuid:=auth.uid();p public.repo_diver_profiles%rowtype;rid uuid:=gen_random_uuid();begin if u is null then raise exception 'You must be logged in';end if;insert into public.repo_diver_profiles(user_id) values(u) on conflict(user_id) do nothing;select * into p from public.repo_diver_profiles where user_id=u;if p_biome not in ('karamja','fremennik','morytania','abyssal','crystal') then raise exception 'Invalid biome';end if;if not (p.unlocked_biomes ? p_biome) then raise exception 'Biome is locked';end if;update public.repo_diver_runs set status='abandoned',completed_at=now() where user_id=u and status='active';insert into public.repo_diver_runs(id,user_id,biome) values(rid,u,p_biome);return query select rid,now();end$$;
create or replace function public.repo_diver_buy_upgrade(p_upgrade text) returns jsonb language plpgsql security definer set search_path=public as $$
declare u uuid:=auth.uid();p public.repo_diver_profiles%rowtype;c public.characters%rowtype;lv int;mx int;base int;cost bigint;eq jsonb;begin if u is null then raise exception 'You must be logged in';end if;if p_upgrade not in ('tank','cargo','harpoon','suit','boost') then raise exception 'Invalid upgrade';end if;insert into public.repo_diver_profiles(user_id) values(u) on conflict(user_id) do nothing;select * into p from public.repo_diver_profiles where user_id=u for update;select * into c from public.characters where user_id=u for update;if not found then raise exception 'Character not found';end if;lv:=coalesce((p.equipment->>p_upgrade)::int,1);mx:=case when p_upgrade='suit' then 5 else 6 end;base:=case p_upgrade when 'tank' then 1800 when 'cargo' then 1600 when 'harpoon' then 2200 when 'suit' then 2800 else 1900 end;if lv>=mx then raise exception 'Upgrade already maxed';end if;cost:=round(base*power(1.65,lv-1));if c.gp<cost then raise exception 'Not enough GP';end if;eq:=jsonb_set(p.equipment,array[p_upgrade],to_jsonb(lv+1),true);update public.characters set gp=gp-cost where user_id=u;update public.repo_diver_profiles set equipment=eq,updated_at=now() where user_id=u;return jsonb_build_object('equipment',eq,'gp',c.gp-cost,'cost',cost);end$$;
create or replace function public.repo_diver_complete_day(p_run_id uuid,p_catches jsonb,p_dishes jsonb,p_max_depth integer,p_customers integer) returns jsonb language plpgsql security definer set search_path=public as $$
declare u uuid:=auth.uid();r public.repo_diver_runs%rowtype;p public.repo_diver_profiles%rowtype;c public.characters%rowtype;item jsonb;id text;q int;fx int:=0;cx int:=0;gold int:=0;countfish int:=0;countdish int:=0;perfect int:=0;fishmap jsonb:='{}'::jsonb;usedmap jsonb:='{}'::jsonb;j jsonb;st jsonb;unlocks jsonb;price int;basecx int;fish_id text;elapsed numeric;begin
 if u is null then raise exception 'You must be logged in';end if;select * into r from public.repo_diver_runs where id=p_run_id and user_id=u for update;if not found then raise exception 'Run not found';end if;if r.status='claimed' then select * into c from public.characters where user_id=u;return jsonb_build_object('duplicate',true,'fishing_xp_awarded',r.fishing_xp,'cooking_xp_awarded',r.cooking_xp,'gp_awarded',r.gp,'fishing_xp',c.fishing_xp,'cooking_xp',c.cooking_xp,'gp',c.gp);end if;if r.status<>'active' then raise exception 'Run is not active';end if;elapsed:=extract(epoch from(now()-r.started_at));if elapsed<12 or elapsed>3600 then raise exception 'Invalid run duration';end if;if jsonb_typeof(coalesce(p_catches,'[]'::jsonb))<>'array' or jsonb_typeof(coalesce(p_dishes,'[]'::jsonb))<>'array' then raise exception 'Invalid results';end if;
 for item in select value from jsonb_array_elements(p_catches) limit 45 loop id:=item->>'id';q:=least(3,greatest(1,coalesce((item->>'q')::int,1)));basecx:=case id when 'shrimp' then 8 when 'sardine' then 12 when 'trout' then 18 when 'mudskipper' then 28 when 'rockcrab' then 34 when 'snapper' then 52 when 'goblinfish' then 60 when 'fremcod' then 22 when 'swordfin' then 38 when 'moonjel' then 58 when 'dragonlob' then 95 when 'ghostshark' then 115 when 'monkfish' then 44 when 'bloodeel' then 72 when 'phantom' then 120 when 'soulangler' then 190 when 'abyssaleel' then 80 when 'runeray' then 128 when 'voidshark' then 210 when 'levifry' then 280 when 'crystaltuna' then 95 when 'crystalmanta' then 150 when 'ancientmanta' then 235 when 'deepkraken' then 320 else 0 end;if basecx=0 then continue;end if;fx:=fx+round(basecx*(1+(q-1)*.12));countfish:=countfish+1;fishmap:=jsonb_set(fishmap,array[id],to_jsonb(coalesce((fishmap->>id)::int,0)+1),true);end loop;
 if countfish>greatest(4,floor(elapsed/2.2)::int) then raise exception 'Catch rate validation failed';end if;
 for item in select value from jsonb_array_elements(p_dishes) limit 30 loop id:=item->>'id';q:=least(4,greatest(1,coalesce((item->>'quality')::int,1)));price:=case id when 'shrimp_skewer' then 42 when 'grilled_trout' then 68 when 'snapper_plate' then 135 when 'lobster_platter' then 245 when 'monk_curry' then 128 when 'ghost_steak' then 285 when 'abyssal_bowl' then 210 when 'rune_ray' then 340 when 'crystal_plate' then 480 when 'ancient_feast' then 720 else 0 end;basecx:=case id when 'shrimp_skewer' then 14 when 'grilled_trout' then 20 when 'snapper_plate' then 34 when 'lobster_platter' then 58 when 'monk_curry' then 40 when 'ghost_steak' then 66 when 'abyssal_bowl' then 54 when 'rune_ray' then 82 when 'crystal_plate' then 110 when 'ancient_feast' then 160 else 0 end;if price=0 then continue;end if;fish_id:=case id when 'shrimp_skewer' then 'shrimp' when 'grilled_trout' then 'trout' when 'snapper_plate' then 'snapper' when 'lobster_platter' then 'dragonlob' when 'monk_curry' then 'monkfish' when 'ghost_steak' then 'ghostshark' when 'abyssal_bowl' then 'abyssaleel' when 'rune_ray' then 'runeray' when 'crystal_plate' then 'crystalmanta' when 'ancient_feast' then 'ancientmanta' else '' end;if coalesce((fishmap->>fish_id)::int,0)<=coalesce((usedmap->>fish_id)::int,0) then continue;end if;usedmap:=jsonb_set(usedmap,array[fish_id],to_jsonb(coalesce((usedmap->>fish_id)::int,0)+1),true);cx:=cx+round(basecx*(case q when 4 then 1.25 when 3 then 1.1 when 2 then .92 else .7 end));gold:=gold+round(price*(case q when 4 then 1.18 when 3 then 1.05 when 2 then .9 else .72 end));countdish:=countdish+1;if q=4 then perfect:=perfect+1;end if;end loop;
 if countdish>countfish or p_customers<countdish then countdish:=least(countdish,countfish,greatest(0,p_customers));cx:=least(cx,countdish*180);gold:=least(gold,countdish*800);end if;fx:=least(fx,3000);cx:=least(cx,2200);gold:=least(gold,6500);
 select * into c from public.characters where user_id=u for update;if not found then raise exception 'Character not found';end if;insert into public.repo_diver_profiles(user_id) values(u) on conflict(user_id) do nothing;select * into p from public.repo_diver_profiles where user_id=u for update;j:=p.fish_journal;for id,q in select key,value::text::int from jsonb_each(fishmap) loop j:=jsonb_set(j,array[id],jsonb_build_object('count',coalesce((j->id->>'count')::int,0)+q,'best_q',greatest(coalesce((j->id->>'best_q')::int,1),1)),true);end loop;st:=jsonb_build_object('deepest',greatest(coalesce((p.stats->>'deepest')::numeric,0),greatest(0,p_max_depth)),'total_fish',coalesce((p.stats->>'total_fish')::int,0)+countfish,'total_revenue',coalesce((p.stats->>'total_revenue')::bigint,0)+gold,'perfect_dishes',coalesce((p.stats->>'perfect_dishes')::int,0)+perfect);update public.characters set fishing_xp=fishing_xp+fx,cooking_xp=cooking_xp+cx,gp=gp+gold where user_id=u returning * into c;unlocks:=p.unlocked_biomes;if p.day_number>=2 then unlocks:=unlocks||'"fremennik"'::jsonb;end if;if p.day_number>=6 then unlocks:=unlocks||'"morytania"'::jsonb;end if;if p.day_number>=11 then unlocks:=unlocks||'"abyssal"'::jsonb;end if;if p.day_number>=17 then unlocks:=unlocks||'"crystal"'::jsonb;end if;update public.repo_diver_profiles set day_number=day_number+1,fish_journal=j,stats=st,unlocked_biomes=(select jsonb_agg(distinct x) from jsonb_array_elements(unlocks) x),restaurant=jsonb_set(restaurant,'{rank}',to_jsonb(least(6,1+floor((day_number+1)/4)::int)),true),updated_at=now() where user_id=u;update public.repo_diver_runs set status='claimed',completed_at=now(),fishing_xp=fx,cooking_xp=cx,gp=gold,summary=jsonb_build_object('fish',countfish,'dishes',countdish,'depth',p_max_depth,'customers',p_customers) where id=p_run_id;return jsonb_build_object('fishing_xp_awarded',fx,'cooking_xp_awarded',cx,'gp_awarded',gold,'fishing_xp',c.fishing_xp,'cooking_xp',c.cooking_xp,'gp',c.gp);end$$;
revoke all on function public.repo_diver_get_profile() from public,anon;revoke all on function public.repo_diver_start_day(text) from public,anon;revoke all on function public.repo_diver_buy_upgrade(text) from public,anon;revoke all on function public.repo_diver_complete_day(uuid,jsonb,jsonb,integer,integer) from public,anon;
grant execute on function public.repo_diver_get_profile() to authenticated;grant execute on function public.repo_diver_start_day(text) to authenticated;grant execute on function public.repo_diver_buy_upgrade(text) to authenticated;grant execute on function public.repo_diver_complete_day(uuid,jsonb,jsonb,integer,integer) to authenticated;notify pgrst,'reload schema';
