-- Run this whole file in Supabase: SQL Editor -> New query -> Run.
-- It keeps the existing shared can counter and adds the small character minigame.

create table if not exists public.counter (
  id integer primary key,
  count integer not null default 0 check (count >= 0)
);
insert into public.counter (id, count) values (1, 0) on conflict (id) do nothing;
alter table public.counter enable row level security;
drop policy if exists "Anyone can read" on public.counter;
create policy "Anyone can read" on public.counter for select to anon, authenticated using (true);

create or replace function public.change_counter(amount integer)
returns integer language plpgsql security definer set search_path = public as $$
declare new_count integer;
begin
  update public.counter set count = greatest(0, count + amount) where id = 1 returning count into new_count;
  return new_count;
end; $$;

create or replace function public.reset_counter()
returns integer language plpgsql security definer set search_path = public as $$
begin update public.counter set count = 0 where id = 1; return 0; end; $$;

grant execute on function public.change_counter(integer) to anon, authenticated;
grant execute on function public.reset_counter() to anon, authenticated;

do $$ begin alter publication supabase_realtime add table public.counter;
exception when duplicate_object then null; end $$;

-- One simple character per browser token. No email or password required.
create table if not exists public.characters (
  id bigint generated by default as identity primary key,
  owner_token uuid not null unique,
  username text not null unique check (char_length(username) between 3 and 16),
  woodcutting_xp integer not null default 0 check (woodcutting_xp >= 0),
  mining_xp integer not null default 0 check (mining_xp >= 0),
  fishing_xp integer not null default 0 check (fishing_xp >= 0),
  collection text[] not null default '{}',
  created_at timestamptz not null default now()
);
alter table public.characters enable row level security;
-- No direct table access is needed; the browser uses the restricted functions below.

create or replace function public.get_character(p_owner_token uuid)
returns table(username text, woodcutting_xp integer, mining_xp integer, fishing_xp integer, collection text[])
language sql security definer set search_path = public as $$
  select c.username, c.woodcutting_xp, c.mining_xp, c.fishing_xp, c.collection
  from public.characters c where c.owner_token = p_owner_token limit 1;
$$;

create or replace function public.create_character(p_owner_token uuid, p_username text)
returns table(username text, woodcutting_xp integer, mining_xp integer, fishing_xp integer, collection text[])
language plpgsql security definer set search_path = public as $$
declare clean_name text;
begin
  clean_name := btrim(p_username);
  if clean_name !~ '^[A-Za-z0-9 _-]{3,16}$' then
    raise exception 'Use 3-16 letters, numbers, spaces, - or _.';
  end if;

  insert into public.characters(owner_token, username)
  values (p_owner_token, clean_name);

  return query select c.username, c.woodcutting_xp, c.mining_xp, c.fishing_xp, c.collection
  from public.characters c where c.owner_token = p_owner_token;
end; $$;

create or replace function public.collect_resource(p_owner_token uuid, p_skill text)
returns table(new_xp integer, xp_gained integer, drop_name text)
language plpgsql security definer set search_path = public as $$
declare
  gain integer;
  updated_xp integer;
  drop_id text := null;
  drop_label text := null;
  roll double precision := random();
begin
  gain := case p_skill when 'woodcutting' then 25 when 'mining' then 35 when 'fishing' then 40 else null end;
  if gain is null then raise exception 'Invalid skill'; end if;

  if p_skill = 'woodcutting' then
    update public.characters set woodcutting_xp = woodcutting_xp + gain where owner_token = p_owner_token returning woodcutting_xp into updated_xp;
  elsif p_skill = 'mining' then
    update public.characters set mining_xp = mining_xp + gain where owner_token = p_owner_token returning mining_xp into updated_xp;
  else
    update public.characters set fishing_xp = fishing_xp + gain where owner_token = p_owner_token returning fishing_xp into updated_xp;
  end if;

  if updated_xp is null then raise exception 'Character not found'; end if;

  -- Roughly 1 in 100 clicks. A duplicate simply leaves the log unchanged.
  if roll < 0.01 then
    if roll < 0.0005 then drop_id := 'golden_dr_pepper'; drop_label := 'Golden Dr Pepper';
    elsif roll < 0.002 then drop_id := 'reinforced_chair'; drop_label := 'Reinforced Chair';
    elsif roll < 0.0045 then drop_id := 'membership_card'; drop_label := 'Membership Card';
    elsif roll < 0.007 then drop_id := 'chair_fragment'; drop_label := 'Chair Fragment';
    else drop_id := 'mini_dr_pepper'; drop_label := 'Mini Dr Pepper'; end if;

    update public.characters
    set collection = case when drop_id = any(collection) then collection else array_append(collection, drop_id) end
    where owner_token = p_owner_token;
  end if;

  return query select updated_xp, gain, drop_label;
end; $$;

-- RuneScape-style level calculator used by the leaderboard.
create or replace function public.level_from_xp(p_xp integer)
returns integer language plpgsql immutable as $$
declare points integer := 0; lvl integer;
begin
  for lvl in 1..98 loop
    points := points + floor(lvl + 300 * power(2::numeric, lvl / 7.0))::integer;
    if p_xp < floor(points / 4.0) then return lvl; end if;
  end loop;
  return 99;
end; $$;

-- Recreate leaderboard after helper exists (safe to run repeatedly).
create or replace function public.get_leaderboard()
returns table(username text, total_level integer)
language sql security definer set search_path = public as $$
  select c.username,
    public.level_from_xp(c.woodcutting_xp) + public.level_from_xp(c.mining_xp) + public.level_from_xp(c.fishing_xp) as total_level
  from public.characters c
  order by 2 desc, (c.woodcutting_xp + c.mining_xp + c.fishing_xp) desc
  limit 10;
$$;

grant execute on function public.get_character(uuid) to anon, authenticated;
grant execute on function public.create_character(uuid, text) to anon, authenticated;
grant execute on function public.collect_resource(uuid, text) to anon, authenticated;
grant execute on function public.get_leaderboard() to anon, authenticated;
