-- CON OF DR PEPPER: USERNAME + PASSWORD ACCOUNT SETUP
-- Run this entire file in Supabase -> SQL Editor -> New query -> Run.
-- IMPORTANT: In Authentication -> Providers -> Email, turn OFF "Confirm email".
-- The site creates a hidden internal email from the username. Visitors only see username/password.

-- Keep/create the shared can counter.
create table if not exists public.counter (
  id integer primary key,
  count integer not null default 0 check (count >= 0)
);
insert into public.counter (id, count) values (1, 0) on conflict (id) do nothing;
alter table public.counter enable row level security;
drop policy if exists "Anyone can read" on public.counter;
create policy "Anyone can read" on public.counter for select to anon, authenticated using (true);

create or replace function public.change_counter(amount integer)
returns integer language plpgsql security definer set search_path = public as $$
declare new_count integer;
begin
  update public.counter set count = greatest(0, count + amount) where id = 1 returning count into new_count;
  return new_count;
end; $$;

create or replace function public.reset_counter()
returns integer language plpgsql security definer set search_path = public as $$
begin update public.counter set count = 0 where id = 1; return 0; end; $$;

grant execute on function public.change_counter(integer) to anon, authenticated;
grant execute on function public.reset_counter() to anon, authenticated;

do $$ begin alter publication supabase_realtime add table public.counter;
exception when duplicate_object then null; end $$;

-- Replace the old browser-token character table with authenticated accounts.
-- This resets old minigame characters, but does not touch the can counter.
drop table if exists public.characters cascade;

create table public.characters (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  username text not null check (username ~ '^[A-Za-z0-9_-]{3,16}$'),
  woodcutting_xp integer not null default 0 check (woodcutting_xp >= 0),
  mining_xp integer not null default 0 check (mining_xp >= 0),
  fishing_xp integer not null default 0 check (fishing_xp >= 0),
  collection text[] not null default '{}',
  created_at timestamptz not null default now()
);
create unique index characters_username_lower_unique on public.characters (lower(username));
alter table public.characters enable row level security;

-- Automatically create one character when a Supabase Auth account is created.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare clean_name text;
begin
  clean_name := btrim(new.raw_user_meta_data ->> 'username');
  if clean_name is null or clean_name !~ '^[A-Za-z0-9_-]{3,16}$' then
    raise exception 'Invalid username';
  end if;

  insert into public.characters (user_id, username)
  values (new.id, clean_name);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.get_my_character()
returns table(username text, woodcutting_xp integer, mining_xp integer, fishing_xp integer, collection text[])
language sql security definer set search_path = public as $$
  select c.username, c.woodcutting_xp, c.mining_xp, c.fishing_xp, c.collection
  from public.characters c
  where c.user_id = auth.uid()
  limit 1;
$$;

create or replace function public.collect_resource(p_skill text)
returns table(new_xp integer, xp_gained integer, drop_name text)
language plpgsql security definer set search_path = public as $$
declare
  gain integer;
  updated_xp integer;
  drop_id text := null;
  drop_label text := null;
  roll double precision := random();
begin
  if auth.uid() is null then raise exception 'You must be logged in'; end if;

  gain := case p_skill when 'woodcutting' then 25 when 'mining' then 35 when 'fishing' then 40 else null end;
  if gain is null then raise exception 'Invalid skill'; end if;

  if p_skill = 'woodcutting' then
    update public.characters set woodcutting_xp = woodcutting_xp + gain where user_id = auth.uid() returning woodcutting_xp into updated_xp;
  elsif p_skill = 'mining' then
    update public.characters set mining_xp = mining_xp + gain where user_id = auth.uid() returning mining_xp into updated_xp;
  else
    update public.characters set fishing_xp = fishing_xp + gain where user_id = auth.uid() returning fishing_xp into updated_xp;
  end if;

  if updated_xp is null then raise exception 'Character not found'; end if;

  if roll < 0.04 then
    if roll < 0.002 then drop_id := 'golden_dr_pepper'; drop_label := 'Golden Dr Pepper';
    elsif roll < 0.007 then drop_id := 'reinforced_chair'; drop_label := 'Reinforced Chair';
    elsif roll < 0.015 then drop_id := 'membership_card'; drop_label := 'Membership Card';
    elsif roll < 0.025 then drop_id := 'chair_fragment'; drop_label := 'Chair Fragment';
    else drop_id := 'mini_dr_pepper'; drop_label := 'Mini Dr Pepper'; end if;

    update public.characters
    set collection = case when drop_id = any(collection) then collection else array_append(collection, drop_id) end
    where user_id = auth.uid();
  end if;

  return query select updated_xp, gain, drop_label;
end; $$;

create or replace function public.level_from_xp(p_xp integer)
returns integer language plpgsql immutable as $$
declare points integer := 0; lvl integer;
begin
  for lvl in 1..98 loop
    points := points + floor(lvl + 300 * power(2::numeric, lvl / 7.0))::integer;
    if p_xp < floor(points / 4.0) then return lvl; end if;
  end loop;
  return 99;
end; $$;

create or replace function public.get_leaderboard()
returns table(username text, total_level integer)
language sql security definer set search_path = public as $$
  select c.username,
    public.level_from_xp(c.woodcutting_xp) + public.level_from_xp(c.mining_xp) + public.level_from_xp(c.fishing_xp) as total_level
  from public.characters c
  order by 2 desc, (c.woodcutting_xp + c.mining_xp + c.fishing_xp) desc
  limit 10;
$$;

grant execute on function public.get_my_character() to authenticated;
grant execute on function public.collect_resource(text) to authenticated;
grant execute on function public.get_leaderboard() to anon, authenticated;
