-- Run once in the Supabase SQL Editor.
-- Safely installs/reinstalls Cooking XP rewards for solo and online shifts.
alter table public.characters
  add column if not exists cooking_xp integer not null default 0;

drop function if exists public.complete_cooking_shift(integer, integer, integer);

create function public.complete_cooking_shift(
  p_score integer,
  p_orders integer,
  p_xp integer
)
returns table(cooking_xp integer, cooking_gained integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_gain integer := least(2500, greatest(0, coalesce(p_xp, 0)));
begin
  if v_uid is null then
    raise exception 'You must be signed in to receive Cooking XP';
  end if;

  update public.characters c
     set cooking_xp = least(13034431, greatest(0, coalesce(c.cooking_xp, 0)) + v_gain)
   where c.user_id = v_uid;

  if not found then
    raise exception 'No character was found for the signed-in account';
  end if;

  return query
  select c.cooking_xp, v_gain
    from public.characters c
   where c.user_id = v_uid
   limit 1;
end;
$$;

revoke all on function public.complete_cooking_shift(integer, integer, integer) from public;
grant execute on function public.complete_cooking_shift(integer, integer, integer) to authenticated;

-- Cooking highscore tables: separate solo and duo boards.
create table if not exists public.cooking_highscores (
  id bigint generated by default as identity primary key,
  mode text not null check (mode in ('solo','duo')),
  owner_user_id uuid not null,
  player1 text not null,
  player2 text,
  team_key text not null,
  team_name text not null,
  score integer not null default 0 check (score >= 0),
  orders integer not null default 0 check (orders >= 0),
  achieved_at timestamptz not null default now(),
  unique (mode, team_key)
);

alter table public.cooking_highscores enable row level security;
drop policy if exists "Cooking highscores are readable" on public.cooking_highscores;
create policy "Cooking highscores are readable" on public.cooking_highscores for select using (true);

create index if not exists cooking_highscores_mode_score_idx
  on public.cooking_highscores(mode, score desc, orders desc, achieved_at asc);

drop function if exists public.submit_cooking_highscore(text, integer, integer, text, text);
create function public.submit_cooking_highscore(
  p_mode text,
  p_score integer,
  p_orders integer,
  p_player1 text,
  p_player2 text default null
)
returns table(is_new_best boolean, rank bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_mode text := lower(coalesce(p_mode,''));
  v_p1 text := left(trim(coalesce(p_player1,'Chef')), 24);
  v_p2 text := left(trim(coalesce(p_player2,'')), 24);
  v_key text;
  v_name text;
  v_old_score integer;
  v_best boolean := false;
begin
  if v_uid is null then raise exception 'You must be signed in to submit a highscore'; end if;
  if v_mode not in ('solo','duo') then raise exception 'Invalid cooking highscore mode'; end if;
  if v_mode='duo' and v_p2='' then raise exception 'Duo highscores require two players'; end if;

  if v_mode='solo' then
    v_key := v_uid::text;
    v_name := v_p1;
  else
    v_key := lower(least(v_p1,v_p2) || '|' || greatest(v_p1,v_p2));
    v_name := least(v_p1,v_p2) || ' + ' || greatest(v_p1,v_p2);
  end if;

  select h.score into v_old_score from public.cooking_highscores h where h.mode=v_mode and h.team_key=v_key;
  v_best := v_old_score is null or greatest(0,coalesce(p_score,0)) > v_old_score;

  insert into public.cooking_highscores(mode,owner_user_id,player1,player2,team_key,team_name,score,orders,achieved_at)
  values(v_mode,v_uid,v_p1,nullif(v_p2,''),v_key,v_name,greatest(0,coalesce(p_score,0)),greatest(0,coalesce(p_orders,0)),now())
  on conflict(mode,team_key) do update set
    player1=excluded.player1,
    player2=excluded.player2,
    team_name=excluded.team_name,
    score=excluded.score,
    orders=excluded.orders,
    owner_user_id=excluded.owner_user_id,
    achieved_at=excluded.achieved_at
  where excluded.score > public.cooking_highscores.score
     or (excluded.score = public.cooking_highscores.score and excluded.orders > public.cooking_highscores.orders);

  return query select v_best, count(*)::bigint + 1
    from public.cooking_highscores h
   where h.mode=v_mode and h.score > greatest(0,coalesce(p_score,0));
end;
$$;

drop function if exists public.get_cooking_highscores(text, integer);
create function public.get_cooking_highscores(p_mode text, p_limit integer default 25)
returns table(team_name text, player1 text, player2 text, score integer, orders integer, achieved_at timestamptz)
language sql
security definer
set search_path = public
as $$
  select h.team_name,h.player1,h.player2,h.score,h.orders,h.achieved_at
    from public.cooking_highscores h
   where h.mode=lower(p_mode)
   order by h.score desc,h.orders desc,h.achieved_at asc
   limit least(100,greatest(1,coalesce(p_limit,25)));
$$;

revoke all on function public.submit_cooking_highscore(text, integer, integer, text, text) from public;
grant execute on function public.submit_cooking_highscore(text, integer, integer, text, text) to authenticated;
grant execute on function public.get_cooking_highscores(text, integer) to authenticated, anon;
