-- Repo Company: Combat difficulties + two-player Runecrafting Rune Pool
alter table public.characters add column if not exists runecrafting_xp integer not null default 0 check (runecrafting_xp >= 0);

-- Replace combat reward RPC so difficulty changes rewards.
drop function if exists public.complete_combat_run(boolean,integer,integer,integer);
drop function if exists public.complete_combat_run(boolean,integer,integer,integer,text);
create function public.complete_combat_run(p_survived boolean,p_kills integer,p_damage integer,p_seconds integer,p_difficulty text default 'medium')
returns table(attack_xp integer,strength_xp integer,defence_xp integer,attack_gained integer,strength_gained integer,defence_gained integer)
language plpgsql security definer set search_path=public as $$
declare mult numeric:=case p_difficulty when 'easy' then .75 when 'hard' then 1.40 else 1 end; a integer;s integer;d integer;
begin
 if auth.uid() is null then raise exception 'Login required'; end if;
 a:=greatest(1,floor((least(greatest(p_kills,0),300)*3 + case when p_survived then 45 else 0 end)*mult));
 s:=greatest(1,floor((least(greatest(p_damage,0),30000)/10 + case when p_survived then 55 else 0 end)*mult));
 d:=greatest(1,floor((least(greatest(p_seconds,0),60)*2 + case when p_survived then 65 else 0 end)*mult));
 update public.characters set attack_xp=attack_xp+a,strength_xp=strength_xp+s,defence_xp=defence_xp+d where user_id=auth.uid()
 returning characters.attack_xp,characters.strength_xp,characters.defence_xp into attack_xp,strength_xp,defence_xp;
 attack_gained:=a;strength_gained:=s;defence_gained:=d;return next;
end$$;
grant execute on function public.complete_combat_run(boolean,integer,integer,integer,text) to authenticated;

create table if not exists public.runecrafting_rooms(
 id bigint generated by default as identity primary key,
 code text unique not null,
 host_user_id uuid not null,
 guest_user_id uuid,
 host_name text not null,
 guest_name text,
 state jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
alter table public.runecrafting_rooms enable row level security;
drop policy if exists rc_rooms_select on public.runecrafting_rooms;
drop policy if exists rc_rooms_insert on public.runecrafting_rooms;
drop policy if exists rc_rooms_update on public.runecrafting_rooms;
create policy rc_rooms_select on public.runecrafting_rooms for select to authenticated using (true);
create policy rc_rooms_insert on public.runecrafting_rooms for insert to authenticated with check (host_user_id=auth.uid());
create policy rc_rooms_update on public.runecrafting_rooms for update to authenticated using (host_user_id=auth.uid() or guest_user_id=auth.uid() or guest_user_id is null) with check (host_user_id=auth.uid() or guest_user_id=auth.uid());
grant select,insert,update on public.runecrafting_rooms to authenticated;
grant usage,select on sequence public.runecrafting_rooms_id_seq to authenticated;

create or replace function public.complete_runecrafting_match(p_won boolean)
returns table(new_xp integer,xp_gained integer) language plpgsql security definer set search_path=public as $$
declare gain integer:=case when p_won then 90 else 35 end;
begin
 if auth.uid() is null then raise exception 'Login required'; end if;
 update public.characters set runecrafting_xp=runecrafting_xp+gain where user_id=auth.uid() returning runecrafting_xp into new_xp;
 xp_gained:=gain;return next;
end$$;
grant execute on function public.complete_runecrafting_match(boolean) to authenticated;

-- Refresh character/profile RPCs with Runecrafting included.
drop function if exists public.get_my_character();
create function public.get_my_character() returns table(username text,woodcutting_xp integer,mining_xp integer,fishing_xp integer,agility_xp integer,slayer_xp integer,attack_xp integer,strength_xp integer,defence_xp integer,sailing_xp integer,runecrafting_xp integer,agility_best_ms integer,collection text[],created_at timestamptz)
language sql security definer set search_path=public as $$ select c.username,c.woodcutting_xp,c.mining_xp,c.fishing_xp,c.agility_xp,c.slayer_xp,c.attack_xp,c.strength_xp,c.defence_xp,c.sailing_xp,c.runecrafting_xp,c.agility_best_ms,c.collection,c.created_at from public.characters c where c.user_id=auth.uid() limit 1 $$;
grant execute on function public.get_my_character() to authenticated;

drop function if exists public.get_public_character(text);
create function public.get_public_character(p_username text) returns table(username text,woodcutting_xp integer,mining_xp integer,fishing_xp integer,agility_xp integer,slayer_xp integer,attack_xp integer,strength_xp integer,defence_xp integer,sailing_xp integer,runecrafting_xp integer,agility_best_ms integer,collection text[],created_at timestamptz)
language sql security definer set search_path=public as $$ select c.username,c.woodcutting_xp,c.mining_xp,c.fishing_xp,c.agility_xp,c.slayer_xp,c.attack_xp,c.strength_xp,c.defence_xp,c.sailing_xp,c.runecrafting_xp,c.agility_best_ms,c.collection,c.created_at from public.characters c where lower(c.username)=lower(p_username) limit 1 $$;
grant execute on function public.get_public_character(text) to anon,authenticated;

create or replace function public.get_leaderboard() returns table(username text,total_level integer) language sql security definer set search_path=public as $$
 select c.username,(public.level_from_xp(c.woodcutting_xp)+public.level_from_xp(c.mining_xp)+public.level_from_xp(c.fishing_xp)+public.level_from_xp(c.agility_xp)+public.level_from_xp(c.slayer_xp)+public.level_from_xp(c.attack_xp)+public.level_from_xp(c.strength_xp)+public.level_from_xp(c.defence_xp)+public.level_from_xp(c.sailing_xp)+public.level_from_xp(c.runecrafting_xp))::integer from public.characters c order by 2 desc,c.username asc limit 100 $$;
grant execute on function public.get_leaderboard() to anon,authenticated;
notify pgrst,'reload schema';
