-- REPO COMPANY PET WARS
-- Run once in Supabase -> SQL Editor after the pet/bank updates.

create table if not exists public.pet_wars (
  id bigint generated by default as identity primary key,
  room_code text not null unique,
  host_user_id uuid not null,
  guest_user_id uuid,
  host_username text not null,
  guest_username text,
  host_pet text not null,
  guest_pet text,
  host_pet_name text not null,
  guest_pet_name text,
  host_wager integer not null check (host_wager between 1 and 1000),
  guest_wager integer check (guest_wager between 1 and 1000),
  host_pick smallint not null check (host_pick in (1,2)),
  guest_pick smallint check (guest_pick in (1,2)),
  location text not null check (location in ('misthalin','asgarnia','kandarin','morytania')),
  status text not null default 'waiting' check (status in ('waiting','fighting','finished','cancelled')),
  started_at timestamptz,
  resolved_at timestamptz,
  winner_slot smallint check (winner_slot in (1,2)),
  host_payout integer not null default 0,
  guest_payout integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.pet_wars enable row level security;
revoke all on public.pet_wars from anon, authenticated;

create or replace function public.pet_war_code()
returns text language sql volatile as $$
  select upper(substr(md5(random()::text || clock_timestamp()::text),1,6));
$$;

create or replace function public.create_pet_war(p_wager integer, p_pick_mine boolean default true)
returns table(room_code text)
language plpgsql security definer set search_path=public as $$
declare
  c public.characters%rowtype;
  v_code text;
  v_name text;
  v_location text;
begin
  if auth.uid() is null then raise exception 'You must be logged in'; end if;
  if p_wager is null or p_wager < 1 or p_wager > 1000 then raise exception 'Wager must be between 1 and 1,000 GP'; end if;
  select * into c from public.characters where user_id=auth.uid() for update;
  if not found then raise exception 'Character not found'; end if;
  if c.active_pet is null then raise exception 'Put a pet out before entering Pet Wars'; end if;
  -- Automatically close and refund any older waiting rooms owned by this player.
  -- This prevents an abandoned room from permanently blocking CREATE FIGHT.
  update public.characters c2
     set gp = coalesce(c2.gp,0) + refunds.total_wager
    from (
      select host_user_id, coalesce(sum(host_wager),0)::integer as total_wager
      from public.pet_wars
      where host_user_id=auth.uid() and status='waiting'
      group by host_user_id
    ) refunds
   where c2.user_id=refunds.host_user_id;

  update public.pet_wars
     set status='cancelled', resolved_at=now()
   where host_user_id=auth.uid() and status='waiting';

  -- Refresh the locked character row after any refund.
  select * into c from public.characters where user_id=auth.uid() for update;
  if coalesce(c.gp,0) < p_wager then raise exception 'You do not have enough GP'; end if;
  v_name=coalesce(nullif(c.pet_names->>c.active_pet,''),replace(initcap(replace(c.active_pet,'pet_','')),'_',' '));
  loop
    v_code=public.pet_war_code();
    exit when not exists(select 1 from public.pet_wars where pet_wars.room_code=v_code);
  end loop;
  v_location=(array['misthalin','asgarnia','kandarin','morytania'])[1+floor(random()*4)::int];
  update public.characters set gp=gp-p_wager where user_id=auth.uid();
  insert into public.pet_wars(room_code,host_user_id,host_username,host_pet,host_pet_name,host_wager,host_pick,location)
  values(v_code,auth.uid(),c.username,c.active_pet,v_name,p_wager,case when p_pick_mine then 1 else 2 end,v_location);
  return query select v_code;
end;$$;

create or replace function public.join_pet_war(p_room_code text,p_wager integer,p_pick_mine boolean default true)
returns table(room_code text)
language plpgsql security definer set search_path=public as $$
declare
  c public.characters%rowtype;
  w public.pet_wars%rowtype;
  v_code text=upper(trim(p_room_code));
  v_name text;
begin
  if auth.uid() is null then raise exception 'You must be logged in'; end if;
  if p_wager is null or p_wager < 1 or p_wager > 1000 then raise exception 'Wager must be between 1 and 1,000 GP'; end if;
  select * into w from public.pet_wars where pet_wars.room_code=v_code for update;
  if not found or w.status<>'waiting' then raise exception 'That fight is no longer waiting'; end if;
  if w.host_user_id=auth.uid() then raise exception 'You cannot fight yourself'; end if;
  select * into c from public.characters where user_id=auth.uid() for update;
  if c.active_pet is null then raise exception 'Put a pet out before entering Pet Wars'; end if;
  if coalesce(c.gp,0) < p_wager then raise exception 'You do not have enough GP'; end if;
  v_name=coalesce(nullif(c.pet_names->>c.active_pet,''),replace(initcap(replace(c.active_pet,'pet_','')),'_',' '));
  update public.characters set gp=gp-p_wager where user_id=auth.uid();
  update public.pet_wars set guest_user_id=auth.uid(),guest_username=c.username,guest_pet=c.active_pet,guest_pet_name=v_name,
    guest_wager=p_wager,guest_pick=case when p_pick_mine then 2 else 1 end,status='fighting',started_at=now()
  where id=w.id;
  return query select v_code;
end;$$;

create or replace function public.get_pet_war(p_room_code text)
returns table(
 room_code text,status text,location text,started_at timestamptz,host_username text,guest_username text,
 host_pet text,guest_pet text,host_pet_name text,guest_pet_name text,host_wager integer,guest_wager integer,
 host_pick smallint,guest_pick smallint,winner_slot smallint,host_payout integer,guest_payout integer
)
language sql security definer set search_path=public as $$
 select w.room_code,w.status,w.location,w.started_at,w.host_username,w.guest_username,w.host_pet,w.guest_pet,
   w.host_pet_name,w.guest_pet_name,w.host_wager,w.guest_wager,w.host_pick,w.guest_pick,w.winner_slot,w.host_payout,w.guest_payout
 from public.pet_wars w
 where w.room_code=upper(trim(p_room_code)) and auth.uid() in (w.host_user_id,w.guest_user_id)
 limit 1;
$$;

create or replace function public.resolve_pet_war(p_room_code text)
returns table(winner_slot smallint,host_payout integer,guest_payout integer)
language plpgsql security definer set search_path=public as $$
declare
 w public.pet_wars%rowtype;
 v_winner smallint;
 v_pot integer;
 v_host_correct boolean;
 v_guest_correct boolean;
 v_total_correct integer;
 v_host_pay integer=0;
 v_guest_pay integer=0;
begin
 if auth.uid() is null then raise exception 'You must be logged in'; end if;
 select * into w from public.pet_wars where room_code=upper(trim(p_room_code)) for update;
 if not found then raise exception 'Fight not found'; end if;
 if auth.uid() not in (w.host_user_id,w.guest_user_id) then raise exception 'Not your fight'; end if;
 if w.status='finished' then return query select w.winner_slot,w.host_payout,w.guest_payout; return; end if;
 if w.status<>'fighting' then raise exception 'Fight is not active'; end if;
 if now() < w.started_at + interval '15 seconds' then raise exception 'The fight is still running'; end if;
 v_winner=case when random()<0.5 then 1 else 2 end;
 v_pot=w.host_wager+coalesce(w.guest_wager,0);
 v_host_correct=w.host_pick=v_winner;
 v_guest_correct=w.guest_pick=v_winner;
 if v_host_correct and v_guest_correct then
   v_total_correct=w.host_wager+w.guest_wager;
   v_host_pay=floor(v_pot::numeric*w.host_wager/v_total_correct)::integer;
   v_guest_pay=v_pot-v_host_pay;
 elsif v_host_correct then v_host_pay=v_pot;
 elsif v_guest_correct then v_guest_pay=v_pot;
 end if;
 if v_host_pay>0 then update public.characters set gp=gp+v_host_pay where user_id=w.host_user_id; end if;
 if v_guest_pay>0 then update public.characters set gp=gp+v_guest_pay where user_id=w.guest_user_id; end if;
 update public.pet_wars set status='finished',resolved_at=now(),winner_slot=v_winner,host_payout=v_host_pay,guest_payout=v_guest_pay where id=w.id;
 return query select v_winner,v_host_pay,v_guest_pay;
end;$$;

create or replace function public.cancel_pet_war(p_room_code text)
returns void language plpgsql security definer set search_path=public as $$
declare w public.pet_wars%rowtype;
begin
 if auth.uid() is null then raise exception 'You must be logged in'; end if;
 select * into w from public.pet_wars where room_code=upper(trim(p_room_code)) for update;
 if not found or w.host_user_id<>auth.uid() then raise exception 'Waiting fight not found'; end if;
 if w.status<>'waiting' then raise exception 'This fight can no longer be cancelled'; end if;
 update public.characters set gp=gp+w.host_wager where user_id=w.host_user_id;
 update public.pet_wars set status='cancelled',resolved_at=now() where id=w.id;
end;$$;

grant execute on function public.create_pet_war(integer,boolean) to authenticated;
grant execute on function public.join_pet_war(text,integer,boolean) to authenticated;
grant execute on function public.get_pet_war(text) to authenticated;
grant execute on function public.resolve_pet_war(text) to authenticated;
grant execute on function public.cancel_pet_war(text) to authenticated;
notify pgrst,'reload schema';
